Repository fylein/fyle-integrations-app, pull requests merged in 2024-09, with the labels that each got.

#923 qbo prepend code import settings page changes
  src/app/branding/c1-branding-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/core/models/branding/feature-configuration.model.ts
  src/app/core/models/common/import-settings.model.ts
  src/app/core/models/qbo/qbo-configuration/qbo-import-setting.model.ts
  src/app/core/models/sage300/sage300-configuration/sage300-import-settings.model.ts
  src/app/core/services/common/mapping.service.ts
  src/app/core/services/qbo/qbo-configuration/qbo-import-settings.service.ts
  src/app/integrations/qbo/qbo-main/qbo-dashboard/qbo-dashboard.component.ts
  src/app/integrations/qbo/qbo-main/qbo-mapping/qbo-base-mapping/qbo-base-mapping.component.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-clone-settings/qbo-clone-settings.component.html
  src/app/integrations/qbo/qbo-onboarding/qbo-clone-settings/qbo-clone-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-import-settings/qbo-import-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-import-settings/qbo-import-settings.component.ts
  src/app/integrations/sage300/sage300-main/sage300-mapping/sage300-base-mapping/sage300-base-mapping.component.html
  src/app/integrations/sage300/sage300-main/sage300-mapping/sage300-base-mapping/sage300-base-mapping.component.ts
  src/app/integrations/sage300/sage300-shared/sage300-export-settings/sage300-export-settings.component.html
  src/app/integrations/sage300/sage300-shared/sage300-import-settings/sage300-import-settings.component.ts
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.ts
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.ts
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.html
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.ts
  src/app/shared/components/input/dropdown/dropdown.component.html
  src/app/shared/components/input/dropdown/dropdown.component.ts
  src/app/shared/components/onboarding/clone-setting/clone-setting-field/clone-setting-field.component.html
  src/app/shared/components/onboarding/clone-setting/clone-setting-field/clone-setting-field.component.ts
Labels: deploy

#932 feat: create sentry release on every prod release
  .github/workflows/production_deployment.yml
  .github/workflows/staging_deployment.yml
Labels: deploy

#930 feat: design changes for account integrations visibility on admin dashoard for c1
  .github/workflows/c1_staging_deployment.yml
  src/app/shared/components/dashboard/dashboard-export-section/dashboard-export-section.component.html
  src/app/shared/components/dashboard/dashboard-export-section/dashboard-export-section.component.ts
Labels: c1_staging_deploy

#933 qbo prepend code changes
  src/app/core/models/qbo/qbo-configuration/qbo-import-setting.model.ts
  src/app/core/services/common/mapping.service.ts
  src/app/integrations/qbo/qbo-main/qbo-dashboard/qbo-dashboard.component.html
  src/app/integrations/qbo/qbo-main/qbo-dashboard/qbo-dashboard.component.ts
  src/app/integrations/qbo/qbo-main/qbo-mapping/qbo-base-mapping/qbo-base-mapping.component.html
  src/app/integrations/qbo/qbo-main/qbo-mapping/qbo-base-mapping/qbo-base-mapping.component.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-clone-settings/qbo-clone-settings.component.html
  src/app/integrations/qbo/qbo-onboarding/qbo-clone-settings/qbo-clone-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-import-settings/qbo-import-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-import-settings/qbo-import-settings.component.ts
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
Labels: deploy, c1_staging_deploy

#944 netsuite import setting tax destination attributite call change
  src/app/integrations/netsuite/netsuite-shared/netsuite-import-settings/netsuite-import-settings.component.ts
Labels: deploy

#954 integration helper improvements
  src/app/integrations/qbd/qbd-main/integrations-spotlight/integrations-spotlight.component.html
  src/app/integrations/qbd/qbd-main/integrations-spotlight/integrations-spotlight.component.scss
  src/app/integrations/qbd/qbd-main/integrations-spotlight/integrations-spotlight.component.ts
  src/app/integrations/qbd/qbd-onboarding/qbd-auto-onboarding/qbd-auto-onboarding.component.html
  src/app/integrations/qbd/qbd-onboarding/qbd-auto-onboarding/qbd-auto-onboarding.component.scss
Labels: deploy

#959 xero c1 error fix
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.ts
Labels: c1_staging_deploy

#962 intacct c1 import settings fix
  src/app/core/models/intacct/intacct-configuration/import-settings.model.ts
Labels: deploy, c1_staging_deploy

#972 chore: Added github action
  .github/pr-checks-config.yml
  .github/pull_request_template.md
  .github/workflows/c1-staging-deployment.yml
  .github/workflows/create-release-branch.yaml
  .github/workflows/hulk-deployment.yaml
  .github/workflows/pr-checks.yml
  .github/workflows/pr-size.yml
  .github/workflows/production-deployment.yml
  .github/workflows/qa-deployment.yml
  .github/workflows/staging-deployment.yml
Labels: size/M

#965 feat: intacct code prepend fixes
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.html
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.ts
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-base-mapping/intacct-base-mapping.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.ts
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.html
  src/app/shared/components/helper/mapping/mapping-card-header/mapping-card-header.component.ts
Labels: deploy, c1_staging_deploy, size/S

#980 fix: intacct remove expense_type from code prepend array
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-base-mapping/intacct-base-mapping.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.ts
Labels: size/XS

#931 test: Export Settings QBO
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.spec.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
  src/app/integrations/qbo/qbo.fixture.ts
Labels: size/XL

#968 test: qbo import settings
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.spec.ts
  src/app/integrations/qbo/qbo-shared/qbo-import-settings/qbo-import-settings.component.spec.ts
  src/app/integrations/qbo/qbo.fixture.ts
Labels: size/L

#970 test: qbo advanced settings
  src/app/integrations/qbo/qbo-shared/qbo-advanced-settings/qbo-advanced-settings.component.spec.ts
  src/app/integrations/qbo/qbo.fixture.ts
Labels: size/XL

#976 basic .value to get().value 4
  src/app/integrations/bamboo-hr/configuration/configuration.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-import-settings/netsuite-import-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-import-settings/netsuite-import-settings.component.ts
  src/app/integrations/qbd/qbd-shared/qbd-advanced-setting/qbd-advanced-setting.component.html
  src/app/integrations/qbd/qbd-shared/qbd-advanced-setting/qbd-advanced-setting.component.ts
  src/app/integrations/qbd/qbd-shared/qbd-export-setting/qbd-export-setting.component.html
  src/app/integrations/qbd/qbd-shared/qbd-export-setting/qbd-export-setting.component.ts
  src/app/integrations/qbd/qbd-shared/qbd-field-mapping/qbd-field-mapping.component.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-clone-settings/qbo-clone-settings.component.html
  src/app/integrations/qbo/qbo-onboarding/qbo-clone-settings/qbo-clone-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-advanced-settings/qbo-advanced-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-advanced-settings/qbo-advanced-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-employee-settings/qbo-employee-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-import-settings/qbo-import-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-import-settings/qbo-import-settings.component.ts
  src/app/integrations/sage300/sage300-onboarding/sage300-onboarding-connector/sage300-onboarding-connector.component.ts
  src/app/integrations/sage300/sage300-shared/sage300-advanced-settings/sage300-advanced-settings.component.html
  src/app/integrations/sage300/sage300-shared/sage300-advanced-settings/sage300-advanced-settings.component.ts
  src/app/integrations/sage300/sage300-shared/sage300-export-settings/sage300-export-settings.component.html
  src/app/integrations/sage300/sage300-shared/sage300-import-settings/sage300-import-settings.component.ts
  src/app/integrations/travelperk/travelperk-shared/travelperk-advanced-settings/travelperk-advanced-settings.component.ts
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.html
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.ts
  src/app/integrations/xero/xero-shared/xero-advanced-settings/xero-advanced-settings.component.html
  src/app/integrations/xero/xero-shared/xero-export-settings/xero-export-settings.component.html
  src/app/integrations/xero/xero-shared/xero-import-settings/xero-import-settings.component.html
  src/app/integrations/xero/xero-shared/xero-import-settings/xero-import-settings.component.ts
  src/app/shared/components/configuration/configuration-custom-field-creation-dialog/configuration-custom-field-creation-dialog.component.html
  src/app/shared/components/configuration/configuration-skip-export/configuration-skip-export.component.ts
  src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.ts
  src/app/shared/components/export-log/export-log-filter/export-log-filter.component.html
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.ts
  src/app/shared/components/si/core/intacct-location-entity/intacct-location-entity.component.ts
  src/app/shared/components/si/helper/skip-export/skip-export.component.ts
Labels: size/L

#982 fix: PR Size CI Version Update
  .github/workflows/pr-size.yml
Labels: size/XS

#983 test: unit test the intacct mapping page
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-base-mapping/intacct-base-mapping.component.spec.ts
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-mapping.component.spec.ts
  src/app/integrations/intacct/intacct.fixture.ts
Labels: size/L

#981 test: intacct dashboard
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.spec.ts
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding.component.spec.ts
Labels: size/M
