Repository fylein/fyle-integrations-app, pull requests merged in 2024-10, with the labels that each got.

#991 chore: Intacct connector page info box for fyle theme
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/branding/content-configuration.model.ts
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.html
Labels: size/XS

#984 test: QBO Dashboard
  src/app/integrations/qbo/qbo-main/qbo-dashboard/qbo-dashboard.component.spec.ts
  src/app/integrations/qbo/qbo.fixture.ts
Labels: size/XL

#996 fix: fix for integrations on admin dashboard when multiple admins are present
  src/app/auth/login/login.component.ts
  src/app/integrations/intacct/intacct.component.ts
  src/app/integrations/netsuite/netsuite.component.ts
  src/app/integrations/qbo/qbo.component.ts
  src/app/integrations/xero/xero.component.ts
Labels: c1_staging_deploy, size/M

#989 test: unit test the intacct export log pages
  src/app/core/services/common/export-log.service.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-completed-export-log/intacct-completed-export-log.component.spec.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-completed-export-log/intacct-completed-export-log.component.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-export-log.component.spec.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-skip-export-log/intacct-skip-export-log.component.spec.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-skip-export-log/intacct-skip-export-log.component.ts
  src/app/integrations/intacct/intacct.fixture.ts
Labels: size/L

#1001 test: intacct export settings init, save, and misc functions
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.spec.ts
  src/app/integrations/intacct/intacct.fixture.ts
Labels: size/L

#994 test: QBO complete export log
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-complete-export-log/qbo-complete-export-log.component.spec.ts
  src/app/integrations/qbo/qbo.fixture.ts
Labels: size/L

#995 test: qbo skipped export log component
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-skipped-export-log/qbo-skipped-export-log.component.spec.ts
  src/app/integrations/qbo/qbo.fixture.ts
Labels: size/M

#1004 test: fix failing tests due to outdated router spies
  src/app/integrations/intacct/intacct.component.spec.ts
  src/app/integrations/qbo/qbo.component.spec.ts
Labels: size/M

#1002 test: intacct export settings watchers
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.spec.ts
Labels: deploy, size/M

#998 test: qbo mapping
  src/app/integrations/qbo/qbo-main/qbo-mapping/qbo-mapping.component.spec.ts
  src/app/integrations/qbo/qbo.fixture.ts
Labels: size/L

#1006 feat: qbd direct post onboarding skipped export log page settings
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-export-log-routing.module.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-skipped-export-log/qbd-direct-skipped-export-log.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-skipped-export-log/qbd-direct-skipped-export-log.component.scss
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-skipped-export-log/qbd-direct-skipped-export-log.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-skipped-export-log/qbd-direct-skipped-export-log.component.ts
Labels: size/XL

#1007 test: unit test intacct import settings initialization
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.spec.ts
  src/app/integrations/intacct/intacct.fixture.ts
Labels: size/L

#1011 fix: intacct prepend code field fix
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.ts
Labels: deploy, size/XS

#1008 feat: Xero Disconnect
  src/app/core/services/xero/xero-core/xero-helper.service.ts
  src/app/integrations/xero/xero-main/xero-main.component.html
  src/app/integrations/xero/xero-main/xero-main.component.ts
Labels: size/S

#1015 fix: intacct css fix
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-advanced-settings/qbo-advanced-settings.component.ts
  src/styles.scss
Labels: size/XS

#999 test: qbo base mapping
  src/app/integrations/qbo/qbo-main/qbo-mapping/qbo-base-mapping/qbo-base-mapping.component.spec.ts
  src/app/integrations/qbo/qbo.fixture.ts
Labels: size/M

#1009 test: intacct import settings save functionality
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.spec.ts
Labels: size/M

#1010 test: intacct import settings watchers
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.spec.ts
Labels: size/M

#1013 test: intacct import settings utility functions
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.spec.ts
  src/app/integrations/intacct/intacct.fixture.ts
Labels: size/M

#1012 test: intacct c1 import settings initialization
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.spec.ts
  src/app/integrations/intacct/intacct.fixture.ts
Labels: size/M

#1018 test: fix flaky test
  src/app/integrations/qbo/qbo-shared/qbo-advanced-settings/qbo-advanced-settings.component.spec.ts
Labels: size/XS

#1020 test: intacct c1 import settings watchers
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.spec.ts
  src/app/integrations/intacct/intacct.fixture.ts
Labels: size/M

#1021 test: intacct c1 import settings util functions
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.spec.ts
  src/app/integrations/intacct/intacct.fixture.ts
Labels: size/M

#1017 feat: Single credit line for Journal Entry
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/branding/content-configuration.model.ts
  src/app/core/models/netsuite/netsuite-configuration/netsuite-advanced-settings.model.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.ts
Labels: size/M

#1022 fix: form value bug fixes
  src/app/core/models/common/advanced-settings.model.ts
  src/app/integrations/business-central/business-central-shared/business-central-advanced-settings/business-central-advanced-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-advanced-settings/business-central-advanced-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-advanced-settings/qbo-advanced-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-advanced-settings/qbo-advanced-settings.component.ts
  src/app/integrations/sage300/sage300-shared/sage300-advanced-settings/sage300-advanced-settings.component.html
  src/app/integrations/sage300/sage300-shared/sage300-advanced-settings/sage300-advanced-settings.component.ts
  src/app/integrations/sage300/sage300-shared/sage300-import-settings/sage300-import-settings.component.ts
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.html
  src/app/shared/components/configuration/configuration-skip-export/configuration-skip-export.component.ts
  src/app/shared/components/si/helper/skip-export/skip-export.component.html
  src/app/shared/components/si/helper/skip-export/skip-export.component.ts
Labels: deploy, size/M

#1032 fix: restrict creation of custom field with merchant name
  src/app/shared/components/configuration/configuration-custom-field-creation-dialog/configuration-custom-field-creation-dialog.component.ts
Labels: size/XS

#1028 refactor: remove duplicate tests
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.spec.ts
Labels: size/M

#1034 fix: patch "Report Title" option to "Report Name" in skip export
  src/app/shared/components/configuration/configuration-skip-export/configuration-skip-export.component.html
  src/app/shared/components/si/helper/skip-export/skip-export.component.html
Labels: size/XS

#1036 feat: Allow single credit JE only for US orgs
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.ts
Labels: size/XS

#1030 feat: Qbd direct import settings testing with api changes
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/common/advanced-settings.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-advanced-settings.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-import-settings.model.ts
  src/app/core/services/common/accounting-export.service.ts
  src/app/core/services/common/dashboard.service.ts
  src/app/core/services/common/export-log.service.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-import-settings.service.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-complete-export-log/qbd-direct-complete-export-log.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-mapping.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.ts
  src/app/shared/components/configuration/configuration-skip-export/configuration-skip-export.component.ts
Labels: size/XL

#1024 test: intacct advanced settings initialization
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.spec.ts
  src/app/integrations/intacct/intacct.fixture.ts
Labels: size/M

#1026 test: intacct advanced settings save functionality
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.spec.ts
Labels: size/M

#1027 test: intacct advanced settings utility functions
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.spec.ts
  src/app/integrations/intacct/intacct.fixture.ts
Labels: size/M

#1035 fix: update qbd mapping page field placeholder
  src/app/shared/components/qbd/mapping/qbd-mapping-table/qbd-mapping-table.component.html
  src/app/shared/components/qbd/mapping/qbd-mapping-table/qbd-mapping-table.component.ts
Labels: size/XS

#1037 test: fix tests for github action
  .github/workflows/unit-test.yml
  karma.conf.js
  package.json
  scripts/setup_branding_config.js
  src/app/core/interceptor/jwt.interceptor.spec.ts
  src/app/core/services/bamboo-hr/bamboo-hr.service.spec.ts
  src/app/core/services/common/api.service.spec.ts
  src/app/core/services/common/auth.service.spec.ts
  src/app/core/services/common/clone-setting.service.spec.ts
  src/app/core/services/org/org.service.spec.ts
  src/app/core/services/travelperk/travelperk.service.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.spec.ts
  src/app/shared/components/qbd/mapping/qbd-mapping-table/qbd-mapping-table.component.spec.ts
Labels: deploy, size/M

#1043 fix: remove AppCues
  src/app/core/services/integration/appcues.service.spec.ts
  src/app/core/services/integration/appcues.service.ts
  src/app/integrations/intacct/intacct.component.spec.ts
  src/app/integrations/intacct/intacct.component.ts
  src/index.html
Labels: size/M

#1048 fix: app compilation / CI errors
  src/app/core/services/common/helper.service.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-advanced-settings.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-export-settings.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-import-settings.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-auth.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-connector.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-helper.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-mappings.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-workspace.service.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-configuration/qbd-direct-configuration.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-complete-export-log/qbd-direct-complete-export-log.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-export-log.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-skipped-export-log/qbd-direct-skipped-export-log.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-main.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-mapping.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-advanced-settings/qbd-direct-onboarding-advanced-settings.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-done/qbd-direct-onboarding-done.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-export-settings/qbd-direct-onboarding-export-settings.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-import-settings/qbd-direct-onboarding-import-settings.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-landing/qbd-direct-onboarding-landing.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-shared.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct.component.spec.ts
Labels: size/M

#1050 fix: qbd direct export settings folder fix
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.ts
Labels: size/XS

#1052 feat: Expose QBD Direct Integration
  .github/workflows/unit-test.yml
  run.sh
  scripts/setup_env.js
  src/app/auth/login/login.component.ts
  src/app/branding/expose-app-config.ts
  src/app/core/models/branding/expose-app-configuration.model.ts
  src/app/core/services/common/helper.service.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-auth.service.ts
Labels: deploy, size/S

#1049 fix: qbd back end fixes
  src/app/core/models/db/task-log.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-advanced-settings.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-import-settings.model.ts
  src/app/core/services/common/accounting-export.service.ts
  src/app/core/services/common/dashboard.service.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-complete-export-log/qbd-direct-complete-export-log.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct.component.ts
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.ts
  src/app/shared/components/export-log/export-log-table/export-log-table.component.html
Labels: size/M
