Repository fylein/fyle-integrations-app, pull requests merged in 2024-05, with the labels that each got.

#779 Allow local dev iframe
  run.sh
  scripts/setup_env.js
  src/app/core/services/common/events.service.ts
Labels: qa_deploy

#780 Fix Export Settings
  src/app/core/models/intacct/intacct-configuration/export-settings.model.ts
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
  src/app/integrations/sage300/sage300-shared/sage300-export-settings/sage300-export-settings.component.ts
  src/app/integrations/xero/xero-shared/xero-export-settings/xero-export-settings.component.ts
Labels: deploy

#781 Fix Intacct date options
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
  src/app/integrations/sage300/sage300-shared/sage300-export-settings/sage300-export-settings.component.html
  src/app/integrations/sage300/sage300-shared/sage300-export-settings/sage300-export-settings.component.ts
  src/app/integrations/xero/xero-shared/xero-export-settings/xero-export-settings.component.ts
Labels: deploy

#778 netsuite fixes
  .eslintrc.json
  src/app/branding/branding-config.ts
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/branding/content-configuration.model.ts
  src/app/core/models/branding/feature-configuration.model.ts
  src/app/core/models/common/helper.model.ts
  src/app/core/models/db/accounting-export.model.ts
  src/app/core/models/db/expense-group.model.ts
  src/app/core/models/netsuite/netsuite-configuration/netsuite-advanced-settings.model.ts
  src/app/core/models/netsuite/netsuite-configuration/netsuite-export-setting.model.ts
  src/app/core/models/netsuite/netsuite-configuration/netsuite-import-setting.model.ts
  src/app/integrations/business-central/business-central-shared/business-central-advanced-settings/business-central-advanced-settings.component.scss
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.scss
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-import-settings/netsuite-custom-segment-dialog/netsuite-custom-segment-dialog.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-import-settings/netsuite-import-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-import-settings/netsuite-import-settings.component.ts
  src/app/integrations/sage300/sage300-shared/sage300-advanced-settings/sage300-advanced-settings.component.scss
  src/app/integrations/travelperk/travelperk-shared/travelperk-advanced-settings/travelperk-advanced-settings.component.scss
  src/app/shared/components/configuration/configuration-text-field/configuration-text-field.component.html
  src/app/shared/components/configuration/configuration-text-field/configuration-text-field.component.ts
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.ts
  src/app/shared/components/netsuite/core/netsuite-subsidiary-mapping/netsuite-subsidiary-mapping.component.html
  src/styles.scss
Labels: deploy

#771 Expose app in different environments
  run.sh
  src/app/branding/config-template.json
  src/app/branding/expose-app-config.ts
  src/app/core/models/branding/branding-configuration.model.ts
  src/app/core/models/branding/expose-app-configuration.model.ts
  src/app/core/services/common/events.service.ts
  src/app/core/services/netsuite/netsuite-core/netsuite-auth.service.ts
  src/app/integrations/landing/landing.component.html
  src/app/integrations/landing/landing.component.ts
Labels: qa_deploy

#789 Fix skip export category
  src/app/shared/components/configuration/configuration-skip-export/configuration-skip-export.component.ts
  src/app/shared/components/si/helper/skip-export/skip-export.component.ts
Labels: deploy

#793 BOOLEAN for skip export, for all integrations except Sage Intacct
  src/app/core/models/common/advanced-settings.model.ts
Labels: deploy

#790 add isNot option for operator in Skip Export
  src/app/shared/components/configuration/configuration-skip-export/configuration-skip-export.component.ts
  src/app/shared/components/si/helper/skip-export/skip-export.component.ts
Labels: deploy

#796 Add iexact
  src/app/core/models/branding/expose-app-configuration.model.ts
  src/app/shared/components/configuration/configuration-skip-export/configuration-skip-export.component.ts
  src/app/shared/components/si/helper/skip-export/skip-export.component.ts
Labels: deploy

#798 Fix export settings validators
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
  src/app/integrations/sage300/sage300-shared/sage300-export-settings/sage300-export-settings.component.ts
Labels: deploy

#788 netsuite flow chart changes
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/common/helper.model.ts
  src/app/core/models/intacct/intacct-configuration/connector.model.ts
  src/app/core/models/netsuite/netsuite-configuration/netsuite-connector.model.ts
  src/app/core/models/netsuite/netsuite-configuration/netsuite-export-setting.model.ts
  src/app/core/models/netsuite/netsuite-configuration/netsuite-onboarding.model.ts
  src/app/core/services/common/export-log.service.ts
  src/app/core/services/common/helper.service.ts
  src/app/core/services/netsuite/netsuite-core/netsuite-connector.service.ts
  src/app/integrations/intacct/intacct-main/intacct-configuration/intacct-configuration-routing.module.ts
  src/app/integrations/intacct/intacct-main/intacct-configuration/intacct-configuration.component.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-configuration/netsuite-configuration-routing.module.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-configuration/netsuite-configuration.component.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-export-log/netsuite-skipped-export-log/netsuite-skipped-export-log.component.ts
  src/app/integrations/netsuite/netsuite-onboarding/netsuite-onboarding-landing/netsuite-onboarding-landing.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.ts
  src/app/shared/components/configuration/preview-dialog/preview-dialog.component.html
  src/app/shared/components/configuration/preview-dialog/preview-dialog.component.ts
  src/app/shared/components/helper/mandatory-error-message/mandatory-error-message.component.html
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.ts
  src/app/shared/components/netsuite/core/netsuite-connector/netsuite-connector.component.html
  src/app/shared/components/netsuite/core/netsuite-connector/netsuite-connector.component.ts
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.html
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.ts
  src/assets/flow-charts/co-netsuite-data-flow.svg
  src/assets/illustrations/netsuite/bill.png
  src/assets/illustrations/netsuite/ccc.png
  src/assets/illustrations/netsuite/expences-report.png
  src/assets/illustrations/netsuite/journal-entry.png
  src/styles.scss
Labels: deploy

#799 Travelperk: advanced settings simple search
  src/app/shared/components/configuration/configuration-mapping-fields/configuration-mapping-fields.component.html
Labels: deploy

#801 Fix categories call for advanced settings: Travelperk
  src/app/core/services/travelperk/travelperk.service.ts
Labels: deploy

#808 netsuite password fix
  src/app/branding/branding-config.ts
  src/app/branding/c1-contents-config.ts
  src/app/core/models/branding/feature-configuration.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/netsuite/netsuite-configuration/netsuite-advanced-settings.model.ts
  src/app/core/services/common/export-log.service.ts
  src/app/integrations/business-central/business-central-onboarding/business-central-onboarding-connector/business-central-onboarding-connector.component.html
  src/app/integrations/business-central/business-central-onboarding/business-central-onboarding-connector/business-central-onboarding-connector.component.ts
  src/app/integrations/intacct/intacct-main/intacct-configuration/intacct-configuration.component.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-configuration/netsuite-configuration.component.ts
  src/app/integrations/netsuite/netsuite-onboarding/netsuite-onboarding-landing/netsuite-onboarding-landing.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-import-settings/netsuite-import-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-import-settings/netsuite-import-settings.component.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-onboarding-connector/qbo-onboarding-connector.component.html
  src/app/integrations/qbo/qbo-onboarding/qbo-onboarding-connector/qbo-onboarding-connector.component.ts
  src/app/integrations/xero/xero-onboarding/xero-onboarding-connector/xero-onboarding-connector.component.ts
  src/app/shared/components/configuration/configuration-connector/configuration-connector.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.scss
  src/app/shared/components/configuration/configuration-text-field/configuration-text-field.component.html
  src/app/shared/components/netsuite/core/netsuite-connector/netsuite-connector.component.html
  src/app/shared/components/netsuite/core/netsuite-subsidiary-mapping/netsuite-subsidiary-mapping.component.html
  src/app/shared/components/netsuite/core/netsuite-subsidiary-mapping/netsuite-subsidiary-mapping.component.ts
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.html
  src/assets/co/coNetsuiteLanding.svg
Labels: deploy, qa_deploy

#823 netsuite export settings fix
  src/app/auth/login/login.component.ts
  src/app/core/models/netsuite/netsuite-configuration/netsuite-export-setting.model.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.html
Labels: deploy

#822 Rename expenses management to Expense Management
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.html
  src/app/integrations/landing/landing.component.html
  src/app/shared/components/configuration/configuration-connector/configuration-connector.component.html
Labels: qa_deploy

#829 Clear Icon for Payment Sync
  src/app/integrations/qbo/qbo-shared/qbo-advanced-settings/qbo-advanced-settings.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.scss
Labels: deploy
