Repository fylein/fyle-integrations-app, pull requests merged in 2024-11, with the labels that each got.

#1045 fix: netsuite > category mapping errors > dialogue > table header text
  src/app/integrations/netsuite/netsuite-main/netsuite-dashboard/netsuite-dashboard.component.ts
Labels: size/XS

#1057 feat: qbd-direct-onboarding-pre-requisite implementation
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-connector.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-onboarding.model.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.scss
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.ts
  src/assets/icons/downloadqbd.svg
  src/assets/icons/expand.svg
  src/assets/sprites/sprite.svg
  tailwind.config.js
Labels: size/M

#1065 feat: qbd direct connector data sync up ts changes
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.ts
Labels: size/XS

#1067 fix: remove sentry transaction sampling
  src/main.ts
Labels: size/XS

#1066 feat: QBD direct main connection page business logic
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-connector.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-onboarding.model.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-connector.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-connector.service.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-connector.service.ts.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-connector.service.ts.service.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-connector.service.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.ts
  src/app/integrations/qbd-direct/qbd-direct.component.ts
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.html
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.ts
  src/assets/fyle/favicon.png
Labels: size/L

#1063 feat: qbd direct connector download file ts changes
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.ts
Labels: size/M

#1062 feat: qbd direct pre requisite ts changes
  src/app/core/models/common/helper.model.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.ts
  src/app/integrations/qbd-direct/qbd-direct.component.ts
  src/app/shared/components/core/svg-icon/svg-icon.component.ts
  src/app/shared/components/input/chechbox-button/chechbox-button.component.ts
Labels: size/M

#1070 Qbd direct connector data sync up ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-connector.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-onboarding.model.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-connector.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-connector.service.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-connector.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-connector.service.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.ts
  src/app/integrations/qbd-direct/qbd-direct.component.ts
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.html
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.ts
  src/assets/fyle/favicon.png
Labels: size/L

#1060 feat: qbd connector setup UI changes
  src/app/core/models/common/helper.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-connector.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-onboarding.model.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-connector.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-connector.service.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-connector.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-connector.service.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.scss
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.scss
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-shared.module.ts
  src/app/integrations/qbd-direct/qbd-direct.component.ts
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.html
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.ts
  src/app/shared/components/configuration/configuration-info-label/configuration-info-label.component.html
  src/app/shared/components/configuration/configuration-info-label/configuration-info-label.component.ts
  src/app/shared/components/core/svg-icon/svg-icon.component.ts
  src/app/shared/components/input/checkbox-button/checkbox-button.component.ts
  src/assets/fyle/favicon.png
  src/assets/icons/co/grv-lock.svg
  src/assets/icons/co/grv-show-hide-medium.svg
  src/assets/icons/co/grv-show-medium.svg
  src/assets/icons/co/grv-upload.svg
  src/assets/icons/eye-medium.svg
  src/assets/icons/eye-slash-medium.svg
  src/assets/icons/lock.svg
  src/assets/icons/upload.svg
  src/assets/sprites/sprite.svg
Labels: size/L

#1059 feat: Download qwd file UI changes
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/common/helper.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-connector.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-onboarding.model.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-connector.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-connector.service.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-connector.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-connector.service.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.scss
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.scss
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.scss
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-shared.module.ts
  src/app/integrations/qbd-direct/qbd-direct.component.ts
  src/app/integrations/qbd-direct/qbd-direct.module.ts
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.html
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.ts
  src/app/shared/components/configuration/configuration-info-label/configuration-info-label.component.html
  src/app/shared/components/configuration/configuration-info-label/configuration-info-label.component.ts
  src/app/shared/components/configuration/configuration-step-footer/configuration-step-footer.component.html
  src/app/shared/components/core/svg-icon/svg-icon.component.ts
  src/app/shared/components/input/checkbox-button/checkbox-button.component.ts
  src/assets/fyle/favicon.png
  src/assets/icons/co/grv-lock.svg
  src/assets/icons/co/grv-show-hide-medium.svg
  src/assets/icons/co/grv-show-medium.svg
  src/assets/icons/co/grv-upload.svg
  src/assets/icons/eye-medium.svg
  src/assets/icons/eye-slash-medium.svg
  src/assets/icons/lock.svg
  src/assets/icons/upload.svg
  src/assets/sprites/sprite.svg
  src/styles.scss
Labels: size/M

#1058 feat: qbd-direct onboarding prerequisite UI implementation
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/common/helper.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-connector.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-onboarding.model.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-connector.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-connector.service.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-connector.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-connector.service.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.scss
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.scss
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.scss
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-shared.module.ts
  src/app/integrations/qbd-direct/qbd-direct.component.ts
  src/app/integrations/qbd-direct/qbd-direct.module.ts
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.html
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.ts
  src/app/shared/components/configuration/configuration-info-label/configuration-info-label.component.html
  src/app/shared/components/configuration/configuration-info-label/configuration-info-label.component.ts
  src/app/shared/components/configuration/configuration-step-footer/configuration-step-footer.component.html
  src/app/shared/components/core/svg-icon/svg-icon.component.ts
  src/app/shared/components/helper/onboarding-stepper/onboarding-stepper.component.scss
  src/app/shared/components/input/checkbox-button/checkbox-button.component.scss
  src/app/shared/components/input/checkbox-button/checkbox-button.component.ts
  src/assets/fyle/favicon.png
  src/assets/icons/co/grv-lock.svg
  src/assets/icons/co/grv-show-hide-medium.svg
  src/assets/icons/co/grv-show-medium.svg
  src/assets/icons/co/grv-upload.svg
  src/assets/icons/download-medium.svg
  src/assets/icons/downloadqbd.svg
  src/assets/icons/expand.svg
  src/assets/icons/eye-medium.svg
  src/assets/icons/eye-slash-medium.svg
  src/assets/icons/lock.svg
  src/assets/icons/upload.svg
  src/assets/sprites/sprite.svg
  src/styles.scss
Labels: size/M

#1056 feat: qbd direct onboarding landing page
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/common/helper.model.ts
  src/app/core/models/db/workspaces.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-connector.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-onboarding.model.ts
  src/app/core/services/common/workspace.service.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-connector.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-connector.service.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-connector.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-connector.service.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-landing/qbd-direct-onboarding-landing.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-landing/qbd-direct-onboarding-landing.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.scss
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.scss
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.scss
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-shared.module.ts
  src/app/integrations/qbd-direct/qbd-direct.component.ts
  src/app/integrations/qbd-direct/qbd-direct.module.ts
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.html
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.ts
  src/app/shared/components/configuration/configuration-info-label/configuration-info-label.component.html
  src/app/shared/components/configuration/configuration-info-label/configuration-info-label.component.ts
  src/app/shared/components/configuration/configuration-step-footer/configuration-step-footer.component.html
  src/app/shared/components/core/svg-icon/svg-icon.component.ts
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.ts
  src/app/shared/components/helper/onboarding-stepper/onboarding-stepper.component.scss
  src/app/shared/components/input/checkbox-button/checkbox-button.component.scss
  src/app/shared/components/input/checkbox-button/checkbox-button.component.ts
  src/assets/flow-charts/fyle-qbd-direct-flow-chart.svg
  src/assets/fyle/favicon.png
  src/assets/icons/co/grv-lock.svg
  src/assets/icons/co/grv-show-hide-medium.svg
  src/assets/icons/co/grv-show-medium.svg
  src/assets/icons/co/grv-upload.svg
  src/assets/icons/download-medium.svg
  src/assets/icons/expand.svg
  src/assets/icons/eye-medium.svg
  src/assets/icons/eye-slash-medium.svg
  src/assets/icons/lock.svg
  src/assets/icons/upload.svg
  src/assets/logos/qbd-direct-logo.svg
  src/assets/sprites/sprite.svg
  src/styles.scss
  tailwind.config.js
Labels: size/M

#1068 fix: xero export settings payload bug
  src/app/core/models/xero/xero-configuration/xero-export-settings.model.ts
Labels: size/XS

#1072 feat: add split expense grouping config to xero clone settings
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.html
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.ts
Labels: size/S

#1071 feat: add split expense grouping config to xero export settings
  src/app/core/models/xero/xero-configuration/xero-export-settings.model.ts
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.html
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.ts
  src/app/integrations/xero/xero-shared/xero-export-settings/xero-export-settings.component.html
  src/app/integrations/xero/xero-shared/xero-export-settings/xero-export-settings.component.ts
Labels: size/M

#1074 fix: fix payload and display of dynamic fields in xero clone settings
  src/app/core/models/xero/xero-configuration/clone-setting.model.ts
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.ts
Labels: size/S

#1077 feat: get 0% default tax
  src/app/integrations/netsuite/netsuite-shared/netsuite-import-settings/netsuite-import-settings.component.ts
Labels: deploy, size/XS

#1080 fix: show either import or export merchants in xero
  src/app/core/models/xero/db/xero-workspace-general-setting.model.ts
  src/app/integrations/xero/xero-shared/xero-advanced-settings/xero-advanced-settings.component.html
  src/app/integrations/xero/xero-shared/xero-import-settings/xero-import-settings.component.html
Labels: size/XS

#1084 fix: qbd direct advanced settings onboarding changes and content changes
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/common/advanced-settings.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-advanced-settings.model.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-advanced-settings/qbd-direct-onboarding-advanced-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-advanced-settings/qbd-direct-onboarding-advanced-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
Labels: size/M

#1083 fix: qbd direct import settings onboarding changes and content changes
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/common/advanced-settings.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-advanced-settings.model.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-advanced-settings/qbd-direct-onboarding-advanced-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-advanced-settings/qbd-direct-onboarding-advanced-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-import-settings/qbd-direct-onboarding-import-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-import-settings/qbd-direct-onboarding-import-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-shared.module.ts
Labels: size/M

#1082 fix: qbd direct export settings onboarding changes and content changes
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/common/advanced-settings.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-advanced-settings.model.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-advanced-settings/qbd-direct-onboarding-advanced-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-advanced-settings/qbd-direct-onboarding-advanced-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-export-settings/qbd-direct-onboarding-export-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-export-settings/qbd-direct-onboarding-export-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-import-settings/qbd-direct-onboarding-import-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-import-settings/qbd-direct-onboarding-import-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-shared.module.ts
Labels: size/M

#1079 feat: support split expense grouping for Netsuite
  src/app/core/models/db/expense-group-setting.model.ts
  src/app/core/models/netsuite/netsuite-configuration/netsuite-export-setting.model.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.ts
Labels: size/S

#1085 fix: QBD direct bug fixes
  src/app/branding/c1-branding-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/core/models/branding/kb-article.model.ts
  src/app/core/models/db/task-log.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/services/common/dashboard.service.ts
  src/app/core/services/common/export-log.service.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-connector.service.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.html
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.html
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.ts
  src/app/shared/components/core/svg-icon/svg-icon.component.ts
  src/assets/icons/check-circle-outline-extra-large.svg
  src/assets/icons/co/grv-checkmark-encircled-extra-large.svg
  src/assets/icons/eye-medium.svg
  src/assets/sprites/sprite.svg
Labels: deploy, size/M

#1078 fix: QA fixes
  src/app/branding/c1-branding-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/branding/kb-article.model.ts
  src/app/core/models/common/advanced-settings.model.ts
  src/app/core/models/db/task-log.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-advanced-settings.model.ts
  src/app/core/services/common/dashboard.service.ts
  src/app/core/services/common/export-log.service.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-connector.service.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-advanced-settings/qbd-direct-onboarding-advanced-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-advanced-settings/qbd-direct-onboarding-advanced-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-export-settings/qbd-direct-onboarding-export-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-export-settings/qbd-direct-onboarding-export-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-import-settings/qbd-direct-onboarding-import-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-import-settings/qbd-direct-onboarding-import-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.scss
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-shared.module.ts
  src/app/integrations/qbd-direct/qbd-direct.component.ts
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.html
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.ts
  src/app/shared/components/configuration/configuration-info-label/configuration-info-label.component.scss
  src/app/shared/components/configuration/configuration-step-footer/configuration-step-footer.component.html
  src/app/shared/components/configuration/configuration-step-footer/configuration-step-footer.component.ts
  src/app/shared/components/configuration/configuration-step-header/configuration-step-header.component.html
  src/app/shared/components/core/svg-icon/svg-icon.component.ts
  src/app/shared/components/input/checkbox-button/checkbox-button.component.html
  src/app/shared/components/input/checkbox-button/checkbox-button.component.scss
  src/app/shared/components/input/checkbox-button/checkbox-button.component.ts
  src/assets/icons/check-circle-outline-extra-large.svg
  src/assets/icons/check-small.svg
  src/assets/icons/co/grv-checkmark-encircled-extra-large.svg
  src/assets/icons/eye-medium.svg
  src/assets/icons/eye-slash-medium.svg
  src/assets/sprites/sprite.svg
Labels: deploy, size/L

#1088 fix: configuration footer fix
  src/app/shared/components/configuration/configuration-step-footer/configuration-step-footer.component.html
Labels: size/XS
