Repository fylein/fyle-integrations-app, pull requests merged in 2024-03, with the labels that each got.

#617 QA: Testing Fixes - Staging - Intacct Whitelabel
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-base-mapping/intacct-base-mapping.component.ts
Labels: deploy

#609 Mappings page advance search
  src/app/core/models/db/mapping.model.ts
  src/app/core/services/common/mapping.service.ts
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-complete-export-log/qbo-complete-export-log.component.html
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-complete-export-log/qbo-complete-export-log.component.ts
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-skipped-export-log/qbo-skipped-export-log.component.html
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.html
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.ts
Labels: deploy

#600 Export Log Advance Search
  src/app/core/models/db/expense-group.model.ts
  src/app/core/models/db/mapping.model.ts
  src/app/core/services/common/export-log.service.ts
  src/app/core/services/common/mapping.service.ts
  src/app/integrations/business-central/business-central-main/business-central-export-log/business-central-skipped-export-log/business-central-skipped-export-log.component.ts
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-complete-export-log/qbo-complete-export-log.component.html
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-complete-export-log/qbo-complete-export-log.component.ts
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-skipped-export-log/qbo-skipped-export-log.component.html
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-skipped-export-log/qbo-skipped-export-log.component.ts
  src/app/integrations/sage300/sage300-main/sage300-export-log/sage300-skipped-export-log/sage300-skipped-export-log.component.ts
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.html
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.ts
Labels: deploy

#624 C1 Intacct Whitelabel : sentence case - 003
  src/app/branding/branding-config.ts
  src/app/core/models/branding/content-configuration.model.ts
  src/app/core/models/branding/feature-configuration.model.ts
  src/app/core/models/intacct/intacct-configuration/intacct-onboarding.model.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-export-log.component.html
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-export-log.component.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-advanced-setting/intacct-onboarding-advanced-setting.component.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-connector/intacct-onboarding-connector.component.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-done/intacct-onboarding-done.component.html
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-export-setting/intacct-onboarding-export-setting.component.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-import-setting/intacct-onboarding-import-setting.component.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-landing/intacct-onboarding-landing.component.html
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-landing/intacct-onboarding-landing.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
  src/app/shared/components/si/core/intacct-location-entity/intacct-location-entity.component.html
  src/app/shared/components/si/core/intacct-location-entity/intacct-location-entity.component.ts
Labels: qa_deploy

#623 fix c1 intacct bugs
  src/app/core/models/db/accounting-export.model.ts
  src/app/core/models/db/expense-group.model.ts
  src/app/core/models/intacct/intacct-configuration/advanced-settings.model.ts
  src/app/core/services/common/dashboard.service.ts
  src/app/core/services/common/export-log.service.ts
  src/app/core/services/common/mapping.service.ts
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-completed-export-log/intacct-completed-export-log.component.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-export-log.component.html
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.scss
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
  src/app/shared/components/dashboard/dashboard-export-log-dialog/dashboard-export-log-dialog.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.ts
  src/app/shared/components/helper/shimmers/shimmers.component.html
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.html
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.ts
Labels: qa_deploy

#619 C1: hideFeatures wrt C1/forIntacct
  src/app/branding/branding-config.ts
  src/app/core/models/branding/content-configuration.model.ts
  src/app/core/models/branding/feature-configuration.model.ts
  src/app/core/models/common/export-settings.model.ts
  src/app/core/models/db/accounting-export.model.ts
  src/app/core/models/db/expense-group.model.ts
  src/app/core/models/db/task-log.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/intacct/intacct-configuration/advanced-settings.model.ts
  src/app/core/models/intacct/intacct-configuration/export-settings.model.ts
  src/app/core/models/intacct/intacct-configuration/intacct-onboarding.model.ts
  src/app/core/services/common/dashboard.service.ts
  src/app/core/services/common/export-log.service.ts
  src/app/core/services/common/mapping.service.ts
  src/app/integrations/intacct/intacct-main/intacct-configuration/intacct-configuration-routing.module.ts
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.html
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-completed-export-log/intacct-completed-export-log.component.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-export-log.component.html
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-export-log.component.ts
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-base-mapping/intacct-base-mapping.component.ts
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-mapping.component.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-advanced-setting/intacct-onboarding-advanced-setting.component.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-connector/intacct-onboarding-connector.component.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-done/intacct-onboarding-done.component.html
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-export-setting/intacct-onboarding-export-setting.component.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-import-setting/intacct-onboarding-import-setting.component.html
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-import-setting/intacct-onboarding-import-setting.component.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-landing/intacct-onboarding-landing.component.html
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-landing/intacct-onboarding-landing.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.scss
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.scss
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-shared.module.ts
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.ts
  src/app/shared/components/dashboard/dashboard-export-log-dialog/dashboard-export-log-dialog.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.ts
  src/app/shared/components/helper/shimmers/shimmers.component.html
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.html
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.ts
  src/app/shared/components/si/core/intacct-location-entity/intacct-location-entity.component.html
  src/app/shared/components/si/core/intacct-location-entity/intacct-location-entity.component.ts
Labels: qa_deploy

#626 Fix expense groups get in Intacct
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.ts
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.ts
Labels: deploy, qa_deploy

#628 Changes around date selection for c1 | typography
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.scss
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-completed-export-log/intacct-completed-export-log.component.scss
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-export-log.component.scss
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-skip-export-log/intacct-skip-export-log.component.scss
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.html
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.scss
  src/app/shared/components/si/core/intacct-location-entity/intacct-location-entity.component.html
  src/app/shared/components/si/core/intacct-location-entity/intacct-location-entity.component.ts
  src/assets/themes/fyle/fdl.scss
Labels: qa_deploy

#629 C1: Intacct (qa sheet items p1)
  src/app/branding/branding-config.ts
  src/app/core/models/branding/content-configuration.model.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-completed-export-log/intacct-completed-export-log.component.html
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-landing/intacct-onboarding-landing.component.html
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.html
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-complete-export-log/qbo-complete-export-log.component.html
  src/assets/flow-charts/co-qbo-data-flow.svg
  src/assets/flow-charts/co-sage-flow-chart.svg
  src/assets/flow-charts/fyle-sage-flow-chart.svg
  src/assets/sprites/sprite.svg
Labels: deploy, qa_deploy

#573 QA fix 1
  src/app/branding/branding-config.ts
  src/app/core/models/branding/demo-video.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/travelperk/travelperk-configuration/travelperk-advanced-settings.model.ts
  src/app/integrations/travelperk/travelperk-main/travelperk-main.component.html
  src/app/integrations/travelperk/travelperk-main/travelperk-main.component.ts
  src/app/integrations/travelperk/travelperk-onboarding/travelperk-onboarding-landing/travelperk-onboarding-landing.component.html
  src/app/integrations/travelperk/travelperk-onboarding/travelperk-onboarding-landing/travelperk-onboarding-landing.component.ts
  src/app/integrations/travelperk/travelperk-shared/travelperk-advanced-settings/travelperk-advanced-settings.component.html
  src/app/integrations/travelperk/travelperk-shared/travelperk-payment-profile-settings/travelperk-payment-profile-settings.component.html
  src/app/integrations/travelperk/travelperk-shared/travelperk.fixture.ts
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
  src/app/shared/components/configuration/configuration-info-label/configuration-info-label.component.scss
  src/app/shared/components/configuration/configuration-mapping-fields/configuration-mapping-fields.component.html
  src/app/shared/components/configuration/configuration-mapping-fields/configuration-mapping-fields.component.scss
  src/app/shared/components/configuration/configuration-mapping-fields/configuration-mapping-fields.component.ts
  src/app/shared/components/configuration/configuration-multi-select/configuration-multi-select.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.scss
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.ts
  src/app/shared/components/configuration/configuration-step-sub-header/configuration-step-sub-header.component.html
  src/app/shared/components/configuration/preview-dialog/preview-dialog.component.html
  src/app/shared/components/helper/app-landing-page-body/app-landing-page-body.component.html
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
  src/app/shared/components/input/search/search.component.html
  src/app/shared/components/input/search/search.component.ts
  src/app/shared/components/menu/main-menu/main-menu.component.html
  src/app/shared/components/menu/main-menu/main-menu.component.ts
  src/assets/flow-charts/travelperk-flow-chart.svg
  src/assets/pngs/preview-screens/travelperk-expense-grouping-preview.png
  src/assets/pngs/preview-screens/travelperk-pps.png
  src/assets/scss/tab-secondary.scss
  src/assets/themes/co/c1dl.scss
  src/assets/themes/fyle/fdl.scss
  src/styles.scss
  tailwind.config.js
Labels: deploy

#630 Fix business central reload issue
  src/app/core/guard/business-central-token.guard.ts
  src/app/integrations/business-central/business-central.component.html
Labels: deploy

#636 Advance search export log page Intacct
  src/app/core/services/common/export-log.service.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-completed-export-log/intacct-completed-export-log.component.html
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-completed-export-log/intacct-completed-export-log.component.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-skip-export-log/intacct-skip-export-log.component.html
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-skip-export-log/intacct-skip-export-log.component.ts
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-skipped-export-log/qbo-skipped-export-log.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.ts
Labels: deploy

#632 QA : Intacct C1 WL
  src/app/branding/branding-config.ts
  src/app/core/models/branding/content-configuration.model.ts
  src/app/core/models/common/export-settings.model.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.html
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.ts
  src/app/shared/components/configuration/configuration-step-header/configuration-step-header.component.html
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.html
  src/app/shared/components/si/core/intacct-location-entity/intacct-location-entity.component.html
  src/assets/illustrations/sageIntacct/coCCCExportTypeTable.svg
  src/assets/illustrations/sageIntacct/fyleCCCExportTypeTable.svg
  src/assets/sprites/sprite.svg
Labels: qa_deploy

#647 Intacct WL: QA Content and SVGs
  src/app/branding/branding-config.ts
  src/app/core/models/branding/content-configuration.model.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-landing/intacct-onboarding-landing.component.html
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
  src/app/shared/components/helper/app-landing-page-body/app-landing-page-body.component.html
  src/app/shared/components/helper/app-landing-page-body/app-landing-page-body.component.ts
  src/assets/co/coIntacctLanding.svg
  src/assets/illustrations/sageIntacct/coBill.svg
  src/assets/illustrations/sageIntacct/coChargeCard.svg
  src/assets/illustrations/sageIntacct/coJournalEntry.svg
  src/assets/sprites/sprite.svg
Labels: qa_deploy

#689 Xero export settings fix
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.html
  src/app/integrations/xero/xero-shared/xero-advanced-settings/xero-advanced-settings.component.html
  src/app/integrations/xero/xero-shared/xero-export-settings/xero-export-settings.component.html
  src/app/integrations/xero/xero-shared/xero-import-settings/xero-import-settings.component.html
  src/app/integrations/xero/xero-shared/xero-import-settings/xero-import-settings.component.ts
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
Labels: deploy

#695 Tenant connection fixes
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/integrations/integrations.model.ts
  src/app/core/models/xero/xero-configuration/xero-onboarding.model.ts
  src/app/core/services/common/events.service.ts
  src/app/core/services/xero/xero-core/xero-auth.service.ts
  src/app/integrations/landing/landing.component.html
  src/app/integrations/landing/landing.component.ts
  src/app/integrations/xero/xero-onboarding/xero-onboarding-connector/xero-onboarding-connector.component.html
  src/app/integrations/xero/xero-onboarding/xero-onboarding-connector/xero-onboarding-connector.component.ts
  src/app/integrations/xero/xero-onboarding/xero-onboarding-landing/xero-onboarding-landing.component.ts
  src/app/integrations/xero/xero-shared/xero-advanced-settings/xero-advanced-settings.component.ts
  src/app/integrations/xero/xero-shared/xero-export-settings/xero-export-settings.component.html
  src/app/integrations/xero/xero-shared/xero-export-settings/xero-export-settings.component.ts
  src/app/integrations/xero/xero-shared/xero-import-settings/xero-import-settings.component.ts
  src/app/integrations/xero/xero.component.ts
  src/app/shared/components/configuration/configuration-connector/configuration-connector.component.html
  src/app/shared/components/configuration/configuration-connector/configuration-connector.component.ts
Labels: deploy

#698 xero import settings COA fix
  src/app/branding/branding-config.ts
  src/app/core/models/branding/content-configuration.model.ts
  src/app/core/models/db/error.model.ts
  src/app/core/models/xero/db/xero-tenant-mapping.model.ts
  src/app/core/models/xero/xero-configuration/xero-advanced-settings.model.ts
  src/app/core/models/xero/xero-configuration/xero-export-settings.model.ts
  src/app/core/models/xero/xero-configuration/xero-import-settings.model.ts
  src/app/integrations/landing/landing.component.html
  src/app/integrations/landing/landing.component.ts
  src/app/integrations/xero/xero-main/xero-dashboard/xero-dashboard.component.html
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.ts
  src/app/integrations/xero/xero-onboarding/xero-onboarding-connector/xero-onboarding-connector.component.html
  src/app/integrations/xero/xero-onboarding/xero-onboarding-connector/xero-onboarding-connector.component.ts
  src/app/integrations/xero/xero-shared/xero-advanced-settings/xero-advanced-settings.component.html
  src/app/integrations/xero/xero-shared/xero-advanced-settings/xero-advanced-settings.component.ts
  src/app/integrations/xero/xero-shared/xero-export-settings/xero-export-settings.component.html
  src/app/integrations/xero/xero-shared/xero-export-settings/xero-export-settings.component.ts
  src/app/integrations/xero/xero-shared/xero-import-settings/xero-import-settings.component.html
  src/app/integrations/xero/xero-shared/xero-import-settings/xero-import-settings.component.ts
  src/app/shared/components/configuration/configuration-connector/configuration-connector.component.html
  src/app/shared/components/configuration/configuration-connector/configuration-connector.component.ts
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.ts
Labels: deploy

#703 Fix landing page
  src/app/core/services/common/events.service.ts
  src/app/integrations/landing/landing.component.html
Labels: qa_deploy
