Repository fylein/fyle-integrations-app, pull requests merged in 2024-12, with the labels that each got.

#1090 fix: show a 'Beta' badge for business central in landing
  src/app/integrations/landing/landing.component.html
  src/app/integrations/landing/landing.component.ts
Labels: size/S

#1089 fix: text changes in business central configuration
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-import-settings/business-central-import-settings.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
Labels: size/XS

#1087 fix: remove export link column from export logs
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-import-settings/business-central-import-settings.component.html
  src/app/integrations/landing/landing.component.html
  src/app/integrations/landing/landing.component.ts
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/export-log/export-log-table/export-log-table.component.html
Labels: size/S

#1092 fix: QA fixes after design team testing
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-configuration/qbd-direct-configuration.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-export-log.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-mapping.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-landing/qbd-direct-onboarding-landing.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.ts
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.html
  src/app/shared/components/helper/app-landing-page-body/app-landing-page-body.component.html
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
  src/app/shared/components/helper/onboarding-done/onboarding-done.component.html
  src/app/shared/components/helper/onboarding-stepper/onboarding-stepper.component.html
  src/styles.scss
Labels: size/M

#1091 feat: Qbd direct je changes
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-export-settings.model.ts
  src/app/core/services/common/mapping.service.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.ts
Labels: size/M

#1093 fix: JE fixes
  src/app/core/models/common/helper.model.ts
  src/app/core/models/db/destination-attribute.model.ts
  src/app/core/models/db/task-log.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-advanced-settings.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-export-settings.model.ts
  src/app/core/services/common/dashboard.service.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.ts
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.ts
Labels: deploy, size/M

#1094 feat: memo structure in xero app
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/xero/xero-configuration/xero-advanced-settings.model.ts
  src/app/integrations/xero/xero-shared/xero-advanced-settings/xero-advanced-settings.component.html
  src/app/integrations/xero/xero-shared/xero-advanced-settings/xero-advanced-settings.component.ts
Labels: size/M

#1086 feat: add card num and employee name
  src/app/core/models/common/advanced-settings.model.ts
  src/app/core/models/netsuite/netsuite-configuration/netsuite-advanced-settings.model.ts
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.ts
  src/app/integrations/qbd/qbd-shared/qbd-advanced-setting/qbd-advanced-setting.component.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-clone-settings/qbo-clone-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-advanced-settings/qbo-advanced-settings.component.spec.ts
  src/app/integrations/qbo/qbo-shared/qbo-advanced-settings/qbo-advanced-settings.component.ts
  src/app/integrations/sage300/sage300-shared/sage300-advanced-settings/sage300-advanced-settings.component.ts
Labels: deploy, size/M

#1097 fix: C1 xero bug fix
  src/app/core/models/xero/xero-configuration/xero-export-settings.model.ts
Labels: size/XS

#1095 fix: qbd direct team testing fixes
  src/app/core/models/db/task-log.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-advanced-settings.model.ts
  src/app/core/services/common/dashboard.service.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.ts
  src/app/shared/components/configuration/configuration-multi-select/configuration-multi-select.component.html
  src/app/shared/components/configuration/configuration-multi-select/configuration-multi-select.component.ts
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
Labels: deploy, size/M

#1098 fix: update default bank a/c options in BC
  src/app/core/models/enum/enum.model.ts
  src/app/core/services/common/mapping.service.ts
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.ts
Labels: size/M

#1099 feat: add multiselect to choose types of accounts to import
  src/app/core/models/business-central/business-central-configuration/business-central-import-settings.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/services/common/mapping.service.ts
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.ts
  src/app/integrations/business-central/business-central-shared/business-central-import-settings/business-central-import-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-import-settings/business-central-import-settings.component.ts
  src/app/integrations/business-central/business-central-shared/business-central-shared.module.ts
  src/app/integrations/business-central/business-central-shared/business-central.fixture.ts
Labels: size/M

#1100 feat: Expose QBD connector app conditionally
  src/app/branding/expose-app-config.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/integrations/integrations.model.ts
  src/app/core/models/org/org.model.ts
  src/app/core/services/org/org.fixture.ts
  src/app/integrations/landing/landing.component.html
  src/app/integrations/landing/landing.component.ts
Labels: size/S

#1102 fix: update orgs to hide business central beta badge from
  src/app/integrations/landing/landing.component.ts
Labels: size/XS

#1103 fix: QBD Dashboard bugs
  src/app/core/models/db/accounting-export.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/services/common/accounting-export.service.ts
  src/app/core/services/common/dashboard.service.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.ts
Labels: deploy, size/S

#1104 fix: QBD landing page
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.ts
Labels: size/XS

#1106 fix: QBD app name references
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.ts
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.ts
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.html
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.ts
  src/app/shared/components/dashboard/dashboard-export-section/dashboard-export-section.component.html
  src/app/shared/components/dashboard/dashboard-export-section/dashboard-export-section.component.ts
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.ts
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.html
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.ts
Labels: size/M

#1101 fix: QBD direct bug fixes
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/common/advanced-settings.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-advanced-settings.model.ts
  src/app/core/services/common/dashboard.service.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-landing/qbd-direct-onboarding-landing.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.html
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.html
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.ts
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.ts
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.ts
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.html
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.ts
  src/assets/flow-charts/fyle-qbd-direct-flow-chart.svg
  src/assets/sprites/sprite.svg
Labels: deploy, size/M

#1108 fix: QBD fixes post testing
  src/app/core/models/db/expense-group.model.ts
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-onboarding.model.ts
  src/app/core/services/common/accounting-export.service.ts
  src/app/core/services/common/export-log.service.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-helper.service.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-main.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-main.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.ts
Labels: size/S

#1107 fix: dashboard error section fixes
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-import-settings.model.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.html
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.ts
Labels: deploy, size/S

#1109 fix: card num in memo
  src/app/core/models/common/advanced-settings.model.ts
Labels: deploy, size/XS

#1110 fix: initialize chart of accounts multiselect when there is no api response
  src/app/core/models/business-central/business-central-configuration/business-central-import-settings.model.ts
Labels: deploy, size/XS

#1111 fix: remove validation temporarily
  .gitignore
  commits.tsv
  deploy_dump.sh
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
Labels: size/S

#1105 fix: remove the posted at date option for ccc expenses grouped by report
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.ts
Labels: size/XS

#1112 fix: dynamic content for xero customize settings
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/branding/content-configuration.model.ts
  src/app/integrations/xero/xero-shared/xero-advanced-settings/xero-advanced-settings.component.html
Labels: size/XS

#1117 fix: update login error flow and fix redirect url
  src/app/integrations/business-central/business-central-onboarding/business-central-onboarding-landing/business-central-onboarding-landing.component.html
  src/app/integrations/business-central/business-central-onboarding/business-central-onboarding-landing/business-central-onboarding-landing.component.ts
Labels: size/XS

#1118 fix: Prod fixes of QBD direct
  commits.tsv
  src/app/branding/c1-branding-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/core/models/branding/kb-article.model.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
Labels: deploy, size/M

#1119 fix: added special conditional checks for intacct and qbo for supporting card num and employee name
  src/app/core/models/common/advanced-settings.model.ts
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.ts
Labels: size/XS

#1120 feat: Expose split grouping option for xero c1
  src/app/integrations/xero/xero-shared/xero-export-settings/xero-export-settings.component.html
Labels: size/XS

#1121 fix: only ccc exports not being saved
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.ts
Labels: size/XS

#1114 fix: add a default bank account field for CCC expenses
  .gitignore
  deploy_dump.sh
  src/app/branding/c1-branding-config.ts
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/branding/content-configuration.model.ts
  src/app/core/models/branding/kb-article.model.ts
  src/app/core/models/business-central/business-central-configuration/business-central-export-setting.model.ts
  src/app/core/models/common/advanced-settings.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.ts
  src/app/integrations/business-central/business-central-shared/business-central.fixture.ts
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
  src/app/integrations/xero/xero-shared/xero-advanced-settings/xero-advanced-settings.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
Labels: deploy, size/M

#1113 fix: restrict JE modules to group by expense only
  .gitignore
  deploy_dump.sh
  src/app/branding/c1-branding-config.ts
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/branding/content-configuration.model.ts
  src/app/core/models/branding/kb-article.model.ts
  src/app/core/models/business-central/business-central-configuration/business-central-export-setting.model.ts
  src/app/core/models/common/advanced-settings.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.ts
  src/app/integrations/business-central/business-central-shared/business-central.fixture.ts
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
  src/app/integrations/xero/xero-shared/xero-advanced-settings/xero-advanced-settings.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
Labels: size/M

#1122 fix: business central beta bugfixes
  src/app/core/models/business-central/business-central-configuration/business-central-export-setting.model.ts
  src/app/core/models/business-central/business-central-configuration/business-central-import-settings.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/integrations/business-central/business-central-onboarding/business-central-onboarding-landing/business-central-onboarding-landing.component.html
  src/app/integrations/business-central/business-central-onboarding/business-central-onboarding-landing/business-central-onboarding-landing.component.ts
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.ts
  src/app/integrations/business-central/business-central-shared/business-central.fixture.ts
Labels: size/M

#1123 fix: hide card number and employee name as options for memo field
  src/app/core/models/common/advanced-settings.model.ts
Labels: size/XS

#1127 fix: fix memo options for C1
  src/app/core/models/netsuite/netsuite-configuration/netsuite-advanced-settings.model.ts
Labels: size/XS

#1128 fixes: qbd direct prod fix
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.ts
Labels: size/XS

#1126 feat: QBD direct tracker update
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/misc/tracking.model.ts
  src/app/core/services/integration/tracking.service.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.ts
Labels: size/M

#1129 fixes: prod fix
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
Labels: size/XS

#1131 feat: Expose iif and beta QBD
  src/app/integrations/landing/landing.component.html
  src/app/integrations/landing/landing.component.ts
Labels: size/M

#1130 fix:QBD direct connection screen prod fix
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.html
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
Labels: deploy, size/XS

#1115 feat: move employee settings to export settings
  src/app/core/models/common/advanced-settings.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/qbo/qbo-configuration/qbo-export-setting.model.ts
  src/app/core/models/qbo/qbo-configuration/qbo-onboarding.model.ts
  src/app/integrations/qbo/qbo-main/qbo-configuration/qbo-configuration-routing.module.ts
  src/app/integrations/qbo/qbo-main/qbo-configuration/qbo-configuration.component.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-clone-settings/qbo-clone-settings.component.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-onboarding-connector/qbo-onboarding-connector.component.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-onboarding-employee-settings/qbo-onboarding-employee-settings.component.html
  src/app/integrations/qbo/qbo-onboarding/qbo-onboarding-employee-settings/qbo-onboarding-employee-settings.component.scss
  src/app/integrations/qbo/qbo-onboarding/qbo-onboarding-employee-settings/qbo-onboarding-employee-settings.component.spec.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-onboarding-employee-settings/qbo-onboarding-employee-settings.component.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-onboarding-routing.module.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-onboarding.module.ts
  src/app/integrations/qbo/qbo-shared/qbo-employee-settings/qbo-employee-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-employee-settings/qbo-employee-settings.component.scss
  src/app/integrations/qbo/qbo-shared/qbo-employee-settings/qbo-employee-settings.component.spec.ts
  src/app/integrations/qbo/qbo-shared/qbo-employee-settings/qbo-employee-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.spec.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-shared.module.ts
  src/app/integrations/qbo/qbo.component.ts
  src/app/integrations/qbo/qbo.fixture.ts
  src/stories/SubMenu.stories.ts
Labels: size/XL

#1133 fix:QBD direct advanced settings fix
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
Labels: size/XS

#1135 fix: Qbd direct dashboard error section fix and video update
  src/app/branding/fyle-branding-config.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.html
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.ts
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.html
Labels: deploy, size/S

#1134 feat: qbd direct tracking for export and sync on click
  src/app/core/models/enum/enum.model.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-helper.service.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-main.component.ts
Labels: size/S
