Repository fylein/fyle-integrations-app, pull requests merged in 2025-06, with the labels that each got.

#1313 feat: Real-time exports, phase 2 - Intacct
  .gitignore
  src/app/core/models/common/advanced-settings.model.ts
  src/app/core/models/intacct/intacct-configuration/advanced-settings.model.ts
  src/app/core/models/netsuite/netsuite-configuration/netsuite-advanced-settings.model.ts
  src/app/core/models/qbo/qbo-configuration/qbo-advanced-setting.model.ts
  src/app/core/models/xero/xero-configuration/xero-advanced-settings.model.ts
  src/app/core/services/common/accounting-export.service.ts
  src/app/core/services/common/export-log.service.ts
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.ts
  src/app/shared/components/configuration/configuration-schedule-export/configuration-schedule-export.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.ts
Labels: size/M

#1323 feat: Real-time exports, phase 2 - QBD
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-advanced-settings.model.ts
  src/app/core/services/common/accounting-export.service.ts
  src/app/core/services/common/export-log.service.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.ts
  src/app/shared/components/configuration/configuration-schedule-export/configuration-schedule-export.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.ts
Labels: size/S

#1322 fix: make the `app_name` payload consistent across apps
  src/app/core/services/common/mapping.service.ts
Labels: size/XS

#1309 feat: Assisted setup for QuickBooks desktop direct integration
  .gitignore
  src/app/branding/c1-branding-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/core/models/branding/kb-article.model.ts
  src/app/core/models/db/workspaces.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-assisted-setup.service.ts
  src/app/integrations/intacct/intacct.fixture.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-landing/qbd-direct-onboarding-landing.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-landing/qbd-direct-onboarding-landing.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-assisted-setup/qbd-direct-assisted-setup.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-assisted-setup/qbd-direct-assisted-setup.component.scss
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-assisted-setup/qbd-direct-assisted-setup.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-assisted-setup/qbd-direct-assisted-setup.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.spec.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.ts
  src/app/shared/components/configuration/configuration-step-footer/configuration-step-footer.component.html
  src/app/shared/components/configuration/configuration-step-footer/configuration-step-footer.component.ts
  src/app/shared/components/core/svg-icon/svg-icon.component.ts
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.ts
  src/app/shared/components/input/outlined-icon-button/outlined-icon-button.component.html
  src/app/shared/components/input/outlined-icon-button/outlined-icon-button.component.scss
  src/app/shared/components/input/outlined-icon-button/outlined-icon-button.component.spec.ts
  src/app/shared/components/input/outlined-icon-button/outlined-icon-button.component.ts
  src/app/shared/shared.module.ts
  src/assets/co/favicon.svg
  src/assets/fyle/favicon.svg
  src/assets/icons/co/grv-agent.svg
  src/assets/icons/headset.svg
  src/assets/icons/user-one.svg
  src/assets/sprites/sprite.svg
  src/styles.scss
  tailwind.config.js
Labels: deploy, size/L

#1325 fix: show the expense / report number option based on the current grouping
  src/app/branding/c1-branding-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/core/models/branding/feature-configuration.model.ts
  src/app/core/models/common/advanced-settings.model.ts
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.ts
Labels: size/M

#1331 fix: quickbooks direct sentence case & consistent appname changes
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-landing/qbd-direct-onboarding-landing.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-assisted-setup/qbd-direct-assisted-setup.component.html
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
Labels: deploy, size/XS

#1335 fix: qbd direct assisted setup article link changes
  src/app/branding/c1-branding-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/core/models/branding/kb-article.model.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-assisted-setup/qbd-direct-assisted-setup.component.ts
Labels: size/XS

#1336 fix(e2e): add aria attributes to intacct import settings switches
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.ts
Labels: size/S

#1337 fix(e2e): add roles to intacct import settings switches
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
Labels: size/XS

#1320 feat: Add customizable top level memo in Intacct
  src/app/branding/c1-branding-config.ts
  src/app/branding/c1-content-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/branding/content-configuration.model.ts
  src/app/core/models/branding/feature-configuration.model.ts
  src/app/core/models/common/advanced-settings.model.ts
  src/app/core/models/db/configuration.model.ts
  src/app/core/models/intacct/db/configuration.model.ts
  src/app/core/models/intacct/intacct-configuration/advanced-settings.model.ts
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.ts
Labels: deploy, size/M

#1332 feat: Real-time exports, phase 2 - Sage
  src/app/core/models/sage300/sage300-configuration/sage300-advanced-settings.model.ts
  src/app/core/services/common/accounting-export.service.ts
  src/app/core/services/common/export-log.service.ts
  src/app/integrations/sage300/sage300-main/sage300-dashboard/sage300-dashboard.component.ts
  src/app/integrations/sage300/sage300-shared/fixture.ts
  src/app/integrations/sage300/sage300-shared/sage300-advanced-settings/sage300-advanced-settings.component.ts
  src/app/shared/components/configuration/configuration-schedule-export/configuration-schedule-export.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.ts
Labels: size/S

#1328 feat: QBD Direct Items Support
  QBD_Direct_Items_Feature_Documentation.md
  QBD_Direct_Items_Feature_Implementation_Plan.md
  QBO_Items_Feature_Documentation.md
  src/app/core/models/qbd-direct/qbd-direct-configuration/qbd-direct-import-settings.model.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.ts
Labels: size/XL

#1340 fix(e2e): add an aria-label to search buttons
  src/app/shared/components/input/search/search.component.html
Labels: size/XS

#1342 fix: QBD items content
  QBD_Direct_Items_Feature_Documentation.md
  QBD_Direct_Items_Feature_Implementation_Plan.md
  QBO_Items_Feature_Documentation.md
  src/app/branding/c1-content-config.ts
  src/app/branding/fyle-contents-config.ts
Labels: size/XL

#1341 fix: Hide next export at for realtime export enabled orgs
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.html
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.spec.ts
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-dashboard/netsuite-dashboard.component.html
  src/app/integrations/netsuite/netsuite-main/netsuite-dashboard/netsuite-dashboard.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/integrations/qbo/qbo-main/qbo-dashboard/qbo-dashboard.component.html
  src/app/integrations/qbo/qbo-main/qbo-dashboard/qbo-dashboard.component.spec.ts
  src/app/integrations/qbo/qbo-main/qbo-dashboard/qbo-dashboard.component.ts
  src/app/integrations/sage300/sage300-main/sage300-dashboard/sage300-dashboard.component.html
  src/app/integrations/sage300/sage300-main/sage300-dashboard/sage300-dashboard.component.ts
  src/app/integrations/xero/xero-main/xero-dashboard/xero-dashboard.component.html
  src/app/integrations/xero/xero-main/xero-dashboard/xero-dashboard.component.ts
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.ts
Labels: size/M

#1353 fix: show bank accounts for JE instead of just credit card accounts -…
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.html
Labels: size/XS

#1354 fix: netsuite export settings validators issue fix for c1
  src/app/core/models/netsuite/netsuite-configuration/netsuite-export-setting.model.ts
Labels: size/XS

#1357 feat: Add codeowners file
  .github/CODEOWNERS
Labels: size/XS

#1351 feat: i18n changes in pipes
  src/app/shared/pipes/search.pipe.ts
  src/app/shared/pipes/sentence-case.pipe.ts
  src/assets/i18n/en.json
Labels: size/S

#1350 feat: i18n changes in services
  src/app/core/services/business-central/business-central-configuration/business-central-onboarding.service.ts
  src/app/core/services/business-central/business-central-core/business-central-helper.service.ts
  src/app/core/services/common/helper.service.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-helper.service.ts
  src/app/core/services/qbo/qbo-core/qbo-auth.service.ts
  src/app/core/services/sage300/sage300-configuration/sage300-export-setting.service.ts
  src/app/core/services/sage300/sage300-configuration/sage300-onboarding.service.ts
  src/app/core/services/sage300/sage300-helper/sage300-helper.service.ts
  src/app/core/services/si/si-core/si-mappings.service.ts
  src/app/core/services/travelperk/travelperk-onboarding.service.ts
  src/app/core/services/xero/xero-core/xero-auth.service.ts
  src/app/integrations/qbd/qbd.component.spec.ts
  src/app/integrations/qbo/qbo.component.spec.ts
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.spec.ts
  src/app/shared/pipes/search.pipe.ts
  src/app/shared/pipes/sentence-case.pipe.ts
  src/assets/i18n/en.json
Labels: size/L

#1360 fix: fix failing unit tests
  src/app/core/models/db/accounting-export.model.ts
  src/app/core/services/common/helper.service.ts
  src/app/integrations/business-central/business-central-main/business-central-export-log/business-central-complete-export-log/business-central-complete-export-log.component.ts
  src/app/integrations/business-central/business-central-main/business-central-mapping/business-central-mapping.component.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-completed-export-log/intacct-completed-export-log.component.ts
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-mapping.component.spec.ts
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-mapping.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-export-log/netsuite-complete-export-logs/netsuite-complete-export-logs.component.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-mapping/netsuite-mapping.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-complete-export-log/qbd-direct-complete-export-log.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-mapping.component.ts
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-complete-export-log/qbo-complete-export-log.component.spec.ts
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-complete-export-log/qbo-complete-export-log.component.ts
  src/app/integrations/qbo/qbo-main/qbo-mapping/qbo-mapping.component.ts
  src/app/integrations/sage300/sage300-main/sage300-export-log/sage300-complete-export-log/sage300-complete-export-log.component.ts
  src/app/integrations/sage300/sage300-main/sage300-mapping/sage300-mapping.component.ts
  src/app/integrations/xero/xero-main/xero-export-log/xero-complete-export-log/xero-complete-export-log.component.ts
  src/app/integrations/xero/xero-main/xero-mapping/xero-mapping.component.ts
  src/app/shared/components/configuration/configuration-multi-select/configuration-multi-select.component.ts
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.ts
  src/app/shared/pipes/search.pipe.spec.ts
  src/app/shared/pipes/sentence-case.pipe.spec.ts
Labels: size/M

#1364 fix: QuickBooks casing in sync data text
  src/assets/i18n/en.json
Labels: size/XS

#1363 fix: fix unit tests
  src/app/core/services/intacct/intacct-configuration/export-settings.service.ts
  src/app/core/services/intacct/intacct-configuration/intacct-onboarding.service.ts
  src/app/core/services/netsuite/netsuite-configuration/netsuite-advanced-settings.service.ts
  src/app/core/services/netsuite/netsuite-configuration/netsuite-export-settings.service.ts
  src/app/core/services/netsuite/netsuite-configuration/netsuite-import-settings.service.ts
  src/app/core/services/netsuite/netsuite-configuration/netsuite-onboarding.service.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-onboarding.service.ts
  src/app/core/services/qbo/qbo-configuration/qbo-onboarding.service.ts
  src/app/core/services/xero/xero-configuration/xero-onboarding.service.ts
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.ts
  src/app/integrations/intacct/intacct-main/intacct-configuration/intacct-configuration.component.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-advanced-setting/intacct-onboarding-advanced-setting.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-configuration/netsuite-configuration.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-import-settings/netsuite-import-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-clone-settings/qbo-clone-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.spec.ts
  src/app/integrations/xero/xero-main/xero-configuration/xero-configuration.component.ts
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.ts
  src/assets/i18n/co/en.json
  src/assets/i18n/fyle/en.json
Labels: size/M
