Repository fylein/fyle-integrations-app, pull requests merged in 2025-04, with the labels that each got.

#1241 fix: vulnerability in vite
  package-lock.json
  package.json
Labels: size/XS

#1234 feat: support standalone cost code imports in intacct import settings
  src/app/core/models/intacct/intacct-configuration/import-settings.model.ts
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.ts
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
Labels: size/M

#1242 fix: make separate API calls for each account type
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.ts
Labels: deploy

#1238 chore: Add Security Scan Workflow
  .github/workflows/security-scan.yml
Labels: size/S

#1244 fix: sentence case all content in config files
  src/app/branding/c1-content-config.ts
  src/app/branding/fyle-contents-config.ts
Labels: size/L

#1182 fix: remove unused flags
  src/app/core/models/db/configuration.model.ts
  src/app/core/models/intacct/db/configuration.model.ts
  src/app/core/models/netsuite/db/netsuite-workspace-general-settings.model.ts
  src/app/core/models/qbd/qbd-configuration/qbd-export-setting.model.ts
  src/app/core/models/qbo/db/workspace-general-setting.model.ts
  src/app/core/models/xero/db/xero-workspace-general-setting.model.ts
  src/app/core/models/xero/xero-configuration/xero-export-settings.model.ts
  src/app/core/services/qbd/qbd-configuration/qbd-export-setting.service.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
  src/app/integrations/intacct/intacct.fixture.ts
  src/app/integrations/qbd/qbd-shared/qbd-export-setting/qbd-export-setting.component.ts
  src/app/integrations/qbd/qbd-shared/qbd-export-setting/qbd-export-setting.fixture.ts
  src/app/integrations/qbo/qbo.fixture.ts
Labels: size/M

#1247 fix: vulnerability in vite
  package-lock.json
  package.json
Labels: size/XS

#1246 fix: qbd_direct-usability-issue
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-advanced-settings/qbd-direct-onboarding-advanced-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-export-settings/qbd-direct-onboarding-export-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-import-settings/qbd-direct-onboarding-import-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.html
  src/app/shared/components/helper/onboarding-stepper/onboarding-stepper.component.html
  src/app/shared/components/helper/onboarding-stepper/onboarding-stepper.component.ts
Labels: size/S

#1248 fix: sentence case all content in html template attributes
  src/app/integrations/bamboo-hr/bamboo-hr.component.html
  src/app/integrations/business-central/business-central-onboarding/business-central-onboarding-connector/business-central-onboarding-connector.component.html
  src/app/integrations/business-central/business-central-onboarding/business-central-onboarding-landing/business-central-onboarding-landing.component.html
  src/app/integrations/business-central/business-central-shared/business-central-advanced-settings/business-central-advanced-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-import-settings/business-central-import-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.html
  src/app/integrations/qbd/qbd-shared/qbd-advanced-setting/qbd-advanced-setting.component.html
  src/app/integrations/qbd/qbd-shared/qbd-export-setting/qbd-export-setting.component.html
  src/app/integrations/qbd/qbd-shared/qbd-field-mapping/qbd-field-mapping.component.html
  src/app/integrations/qbo/qbo-onboarding/qbo-clone-settings/qbo-clone-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-advanced-settings/qbo-advanced-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-import-settings/qbo-import-settings.component.html
  src/app/integrations/sage300/sage300-onboarding/sage300-onboarding-connector/sage300-onboarding-connector.component.html
  src/app/integrations/sage300/sage300-onboarding/sage300-onboarding-landing/sage300-onboarding-landing.component.html
  src/app/integrations/sage300/sage300-shared/sage300-advanced-settings/sage300-advanced-settings.component.html
  src/app/integrations/sage300/sage300-shared/sage300-export-settings/sage300-export-settings.component.html
  src/app/integrations/sage300/sage300-shared/sage300-import-settings/sage300-import-settings.component.html
  src/app/integrations/travelperk/travelperk-onboarding/travelperk-onboarding-landing/travelperk-onboarding-landing.component.html
  src/app/integrations/travelperk/travelperk-shared/travelperk-advanced-settings/travelperk-advanced-settings.component.html
  src/app/integrations/travelperk/travelperk-shared/travelperk-payment-profile-settings/travelperk-payment-profile-settings.component.html
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.html
  src/app/integrations/xero/xero-shared/xero-advanced-settings/xero-advanced-settings.component.html
  src/app/integrations/xero/xero-shared/xero-export-settings/xero-export-settings.component.html
  src/app/integrations/xero/xero-shared/xero-import-settings/xero-import-settings.component.html
  src/app/shared/components/configuration/configuration-custom-field-creation-dialog/configuration-custom-field-creation-dialog.component.html
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
  src/app/shared/components/configuration/configuration-mapping-fields/configuration-mapping-fields.component.html
  src/app/shared/components/configuration/configuration-schedule-export/configuration-schedule-export.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/configuration/configuration-skip-export/configuration-skip-export.component.html
  src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.html
  src/app/shared/components/export-log/export-log-table/export-log-table.component.html
  src/app/shared/components/helper/app-landing-page-body/app-landing-page-body.component.html
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
  src/app/shared/components/helper/zero-state/zero-state.component.html
  src/app/shared/components/netsuite/core/netsuite-connector/netsuite-connector.component.html
  src/app/shared/components/si/helper/skip-export/skip-export.component.html
Labels: size/L

#1250 fix: Update to dummy token in tests
  src/app/core/interceptor/jwt.interceptor.spec.ts
Labels: size/XS

#1255 fix: Appcues props
  src/app/core/services/integration/appcues.service.ts
Labels: size/XS

#1252 feat: token-expiry-detection
  src/app/core/guard/qbo-token.guard.ts
  src/app/core/guard/xero-token.guard.ts
  src/app/core/services/qbo/qbo-configuration/qbo-connector.service.ts
  src/app/core/services/xero/xero-configuration/xero-connector.service.ts
  src/app/integrations/qbo/qbo-routing.module.ts
  src/app/integrations/xero/xero-routing.module.ts
Labels: size/M

#1239 feat: q1_update_token_expired_screen_qbo_xero
  src/app/core/guard/qbo-token.guard.ts
  src/app/core/guard/xero-token.guard.ts
  src/app/core/services/qbo/qbo-configuration/qbo-connector.service.ts
  src/app/core/services/qbo/qbo-core/qbo-auth.service.ts
  src/app/core/services/xero/xero-configuration/xero-connector.service.ts
  src/app/core/services/xero/xero-core/xero-auth.service.ts
  src/app/integrations/qbo/qbo-main/qbo-dashboard/qbo-dashboard.component.html
  src/app/integrations/qbo/qbo-main/qbo-dashboard/qbo-dashboard.component.ts
  src/app/integrations/qbo/qbo-main/qbo-main.component.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-onboarding-landing/qbo-onboarding-landing.component.spec.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-onboarding-landing/qbo-onboarding-landing.component.ts
  src/app/integrations/qbo/qbo-routing.module.ts
  src/app/integrations/qbo/qbo.component.spec.ts
  src/app/integrations/xero/xero-main/xero-dashboard/xero-dashboard.component.html
  src/app/integrations/xero/xero-main/xero-dashboard/xero-dashboard.component.ts
  src/app/integrations/xero/xero-onboarding/xero-onboarding-landing/xero-onboarding-landing.component.ts
  src/app/integrations/xero/xero-routing.module.ts
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.html
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.scss
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.spec.ts
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.ts
  src/app/shared/components/menu/main-menu/main-menu.component.html
  src/app/shared/components/menu/main-menu/main-menu.component.ts
  src/app/shared/shared.module.ts
  src/assets/illustrations/login.svg
Labels: size/L

#1257 fix: figma size alignments
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.html
  src/app/shared/components/menu/main-menu/main-menu.component.ts
Labels: size/S

#1258 fix: update font size and colors to match figma design on disconnect/token page.
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.html
Labels: size/M

#1259 fix: text alignment
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.html
Labels: size/XS

#1260 fix: qbo-health-guard issue
  src/app/core/guard/qbo-token.guard.ts
Labels: size/XS

#1261 fix: disconect-button-redirection
  src/app/core/services/qbo/qbo-core/qbo-helper.service.ts
  src/app/core/services/xero/xero-core/xero-helper.service.ts
  src/app/integrations/qbo/qbo-main/qbo-main.component.ts
  src/app/integrations/xero/xero-main/xero-main.component.ts
Labels: size/XS

#1262 fix: c1 bg-color-fix-tokenexpired-dashboard
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.html
Labels: size/XS

#1263 fix:api-url-token-dashboard
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.ts
Labels: size/XS

#1264 fix: API url in re connection
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.ts
Labels: deploy, size/XS

#1265 feat: changes to debit expense export module in export settings page
  src/app/branding/c1-content-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/common/helper.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/qbo/qbo-configuration/qbo-export-setting.model.ts
  src/app/core/services/common/mapping.service.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.ts
Labels: size/S

#1266 feat: corporate card mapping changes for debit card expense module
  src/app/core/models/db/generic-mapping.model.ts
  src/app/core/services/common/mapping.service.ts
  src/app/integrations/qbo/qbo-main/qbo-mapping/qbo-base-mapping/qbo-base-mapping.component.html
  src/app/integrations/qbo/qbo-main/qbo-mapping/qbo-base-mapping/qbo-base-mapping.component.ts
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.ts
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.html
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.ts
Labels: size/S

#1267 fix: changed travelperk old logo to new updated logo
  src/assets/flow-charts/travelperk-flow-chart.svg
  src/assets/logos/travelperk-logo.png
  src/assets/logos/travelperk-logo.svg
Labels: size/M

#1269 fix: QBD sentence fix on export settings
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.html
Labels: size/XS

#1268 fix: Updated flowchart images with new sentence case formatting for all integrations
  src/assets/flow-charts/bamboo-hr-flow-chart.svg
  src/assets/flow-charts/fyle-netsuite-data-flow.svg
  src/assets/flow-charts/fyle-qbd-direct-flow-chart.svg
  src/assets/flow-charts/fyle-qbo-data-flow.svg
  src/assets/flow-charts/fyle-sage-flow-chart.svg
  src/assets/flow-charts/fyle-xero-data-flow.svg
  src/assets/flow-charts/ms-dynamics-flow-chart.svg
  src/assets/flow-charts/sage300-flow-chart.svg
Labels: size/XL

#1271 fix: QBO mapping page API params fixing
  src/app/core/models/db/mapping.model.ts
  src/app/core/services/common/mapping.service.ts
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.ts
Labels: size/XS

#1272 fix: bank account field not showing for checks and JEs
  src/app/core/models/qbo/qbo-configuration/qbo-export-setting.model.ts
  src/app/core/services/qbo/qbo-configuration/qbo-export-settings.service.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-clone-settings/qbo-clone-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
Labels: deploy, size/S

#1276 fix: dynamically update bank sub-label for JEs and checks
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.html
Labels: size/XS

#1275 fix: allow a couple exceptions for `posted_at`
  src/app/core/models/common/export-settings.model.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.ts
Labels: size/S

#1274 fix: clear invalid date values across all apps
  src/app/core/models/common/export-settings.model.ts
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
  src/app/integrations/sage300/sage300-shared/sage300-export-settings/sage300-export-settings.component.ts
Labels: size/L

#1273 fix: revert standardization for Sage 300
  src/app/core/models/common/export-settings.model.ts
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
  src/app/integrations/sage300/sage300-shared/sage300-export-settings/sage300-export-settings.component.ts
Labels: size/L

#1253 fix: standardize export dates across all apps
  .github/workflows/c1-staging-deployment.yml
  .github/workflows/qa-deployment.yml
  src/app/core/models/common/export-settings.model.ts
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.spec.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
  src/app/integrations/qbo/qbo.fixture.ts
  src/app/integrations/sage300/sage300-shared/sage300-export-settings/sage300-export-settings.component.ts
  src/app/integrations/xero/xero-shared/xero-export-settings/xero-export-settings.component.ts
Labels: deploy, size/L

#1281 fix: intacct export url
  src/app/core/models/db/accounting-export.model.ts
Labels: deploy, size/XS

#1283 fix: Intacct Task Log get
  src/app/core/models/db/task-log.model.ts
  src/app/core/services/common/dashboard.service.ts
Labels: size/XS
