Repository fylein/fyle-integrations-app, pull requests merged in 2025-10, with the labels that each got.

#1544 feat: info tooltips, preview modal
  src/app/core/models/sage50/sage50-configuration/sage50-export-settings.model.ts
  src/app/core/services/sage50/sage50-configuration/sage50-export-settings.service.ts
  src/app/integrations/sage50/sage50-shared/sage50-export-settings/sage50-export-settings.component.html
  src/app/integrations/sage50/sage50-shared/sage50-export-settings/sage50-export-settings.component.ts
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.ts
  src/assets/i18n/en.json
  src/assets/pngs/preview-screens/sage50-payment-method.png
Labels: size/M

#1543 fix: check for missing accounts / vendors and add them to options
  src/app/core/models/sage50/sage50-configuration/sage50-export-settings.model.ts
  src/app/core/services/sage50/sage50-configuration/sage50-export-settings.service.ts
  src/app/integrations/sage50/sage50-shared/sage50-export-settings/sage50-export-settings.component.html
  src/app/integrations/sage50/sage50-shared/sage50-export-settings/sage50-export-settings.component.ts
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.ts
  src/assets/i18n/en.json
  src/assets/pngs/preview-screens/sage50-payment-method.png
Labels: size/M

#1542 feat: export settings - save and persist
  src/app/core/models/sage50/sage50-configuration/sage50-export-settings.model.ts
  src/app/core/services/sage50/sage50-configuration/sage50-export-settings.service.ts
  src/app/integrations/sage50/sage50-shared/sage50-export-settings/sage50-export-settings.component.html
  src/app/integrations/sage50/sage50-shared/sage50-export-settings/sage50-export-settings.component.ts
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.ts
  src/assets/i18n/en.json
  src/assets/pngs/preview-screens/sage50-payment-method.png
Labels: size/M

#1537 feat: text field component for export settings
  src/app/core/models/sage50/sage50-configuration/sage50-export-settings.model.ts
  src/app/core/services/sage50/sage50-configuration/sage50-export-settings.service.ts
  src/app/integrations/sage50/sage50-shared/sage50-export-settings/sage50-export-settings.component.html
  src/app/integrations/sage50/sage50-shared/sage50-export-settings/sage50-export-settings.component.ts
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.ts
  src/app/shared/components/configuration/configuration-text-field/configuration-text-field.component.html
  src/app/shared/components/configuration/configuration-text-field/configuration-text-field.component.scss
  src/app/shared/components/configuration/configuration-text-field/configuration-text-field.component.ts
  src/assets/i18n/en.json
  src/assets/icons/warning-filled.svg
  src/assets/pngs/preview-screens/sage50-payment-method.png
Labels: size/L

#1534 feat: support for new onboarding states
  src/app/core/models/enum/enum.model.ts
  src/app/core/services/common/csv-json-translator.service.ts
  src/app/core/services/common/workspace.service.ts
  src/app/core/services/sage50/sage50-configuration/sage50-onboarding.service.ts
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-landing/sage50-onboarding-landing.component.html
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-landing/sage50-onboarding-landing.component.ts
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.ts
  src/app/integrations/sage50/sage50.component.ts
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.ts
Labels: size/S

#1547 feat: sage 50 export settings
  src/app/branding/c1/branding-config.ts
  src/app/branding/fyle/branding-config.ts
  src/app/core/models/branding/kb-article.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/sage50/db/sage50-workspace.model.ts
  src/app/core/models/sage50/sage50-configuration/sage50-export-settings.model.ts
  src/app/core/services/common/export-settings.service.ts
  src/app/core/services/common/mapping.service.ts
  src/app/core/services/netsuite/netsuite-configuration/netsuite-export-settings.service.ts
  src/app/core/services/qbo/qbo-configuration/qbo-export-settings.service.ts
  src/app/core/services/sage50/sage50-configuration/sage50-export-settings.service.ts
  src/app/core/services/sage50/sage50-mapping.service.ts
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.html
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding.component.html
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding.component.scss
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding.component.ts
  src/app/integrations/sage50/sage50-routing.ts
  src/app/integrations/sage50/sage50-shared/sage50-export-settings/sage50-export-settings.component.html
  src/app/integrations/sage50/sage50-shared/sage50-export-settings/sage50-export-settings.component.scss
  src/app/integrations/sage50/sage50-shared/sage50-export-settings/sage50-export-settings.component.ts
  src/app/integrations/sage50/sage50.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.ts
  src/app/shared/components/configuration/configuration-step-header/configuration-step-header.component.html
  src/app/shared/components/configuration/configuration-text-field/configuration-text-field.component.html
  src/app/shared/components/configuration/configuration-text-field/configuration-text-field.component.scss
  src/app/shared/components/configuration/configuration-text-field/configuration-text-field.component.ts
  src/app/shared/components/configuration/configuration-toggle-field/configuration-toggle-field.component.html
  src/assets/i18n/en.json
  src/assets/icons/warning-filled.svg
  src/assets/pngs/preview-screens/sage50-payment-method.png
Labels: size/XL

#1551 fix: dashboard export summary button click not working
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.html
Labels: size/XS

#1552 fix: mappings page destination attributes
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.ts
Labels: staging_deploy, size/XS
