Repository fylein/fyle-integrations-app, pull requests merged in 2025-01, with the labels that each got.

#1132 feat: Travelperk Guard
  src/app/core/guard/travelperk-token.guard.ts
  src/app/core/models/qbo/qbo-configuration/qbo-export-setting.model.ts
  src/app/core/services/travelperk/travelperk.service.ts
  src/app/integrations/qbo/qbo-main/qbo-mapping/qbo-mapping.component.spec.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.spec.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
  src/app/integrations/travelperk/travelperk-onboarding/travelperk-onboarding-routing.module.ts
  src/app/integrations/travelperk/travelperk-routing.module.ts
Labels: deploy, size/M

#1137 fix: employee setting handling for employee field mapping
  src/app/core/models/qbo/qbo-configuration/qbo-employee-setting.model.ts
Labels: size/XS

#1138 fix: update incorrect memo structure key in sage300 advanced settings payload
  src/app/core/models/sage300/sage300-configuration/sage300-advanced-settings.model.ts
  src/app/integrations/sage300/sage300-shared/fixture.ts
Labels: size/XS

#1136 fix: qbd direct connector 2.2 step file download fix
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
Labels: size/XS

#1148 fix: Add an "Export Date" option to QBO CCP date options
  src/app/integrations/qbo/qbo-onboarding/qbo-clone-settings/qbo-clone-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
Labels: size/S

#1149 fix: incorrect URL for `/integrations` call and rendering errors
  src/app/core/services/common/integrations.service.ts
  src/app/integrations/landing-v2/landing-v2.component.ts
Labels: size/XS

#1145 fix: update route name and keep `exposeC1Apps`
  src/app/core/services/common/integrations.service.ts
  src/app/integrations/integrations-routing.module.ts
  src/app/integrations/landing-v2/landing-v2.component.html
  src/app/integrations/landing-v2/landing-v2.component.ts
  src/assets/logos/intacct-logo-new.png
  src/assets/logos/intacct-logo.png
  src/assets/logos/netsuite-logo-new.png
  src/assets/logos/netsuite-logo.png
  src/assets/logos/xero-logo-new.png
  src/assets/logos/xero-logo.png
Labels: deploy, c1_staging_deploy, size/XS

#1143 feat: fetch data from integrations API and show connected apps
  src/app/core/models/integrations/integrations.model.ts
  src/app/core/services/common/integrations.service.spec.ts
  src/app/core/services/common/integrations.service.ts
  src/app/integrations/integrations-routing.module.ts
  src/app/integrations/landing-v2/landing-v2.component.html
  src/app/integrations/landing-v2/landing-v2.component.ts
  src/assets/logos/intacct-logo-new.png
  src/assets/logos/intacct-logo.png
  src/assets/logos/netsuite-logo-new.png
  src/assets/logos/netsuite-logo.png
  src/assets/logos/xero-logo-new.png
  src/assets/logos/xero-logo.png
Labels: size/M

#1144 feat: UI for the new "Conencted" badge
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/integrations/integrations.model.ts
  src/app/core/services/common/integrations.service.spec.ts
  src/app/core/services/common/integrations.service.ts
  src/app/integrations/integrations-routing.module.ts
  src/app/integrations/landing-v2/landing-v2.component.html
  src/app/integrations/landing-v2/landing-v2.component.ts
  src/app/shared/components/core/badge/badge.component.scss
  src/assets/logos/intacct-logo-new.png
  src/assets/logos/intacct-logo.png
  src/assets/logos/netsuite-logo-new.png
  src/assets/logos/netsuite-logo.png
  src/assets/logos/xero-logo-new.png
  src/assets/logos/xero-logo.png
Labels: size/M

#1142 feat: add CTA and shadow animation on tile hover
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/integrations/integrations.model.ts
  src/app/core/services/common/integrations.service.spec.ts
  src/app/core/services/common/integrations.service.ts
  src/app/integrations/integrations-routing.module.ts
  src/app/integrations/landing-v2/landing-v2.component.html
  src/app/integrations/landing-v2/landing-v2.component.scss
  src/app/integrations/landing-v2/landing-v2.component.ts
  src/app/shared/components/core/badge/badge.component.scss
  src/assets/logos/bamboo-hr-logo.png
  src/assets/logos/intacct-logo-new.png
  src/assets/logos/netsuite-logo-new.png
  src/assets/logos/sage300-logo.png
  src/assets/logos/travelperk-logo.png
  src/assets/logos/xero-logo-new.png
Labels: size/M

#1141 feat: responsive grid layout + new tile layout
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/integrations/integrations.model.ts
  src/app/core/services/common/integrations.service.spec.ts
  src/app/core/services/common/integrations.service.ts
  src/app/integrations/integrations-routing.module.ts
  src/app/integrations/landing-v2/landing-v2.component.html
  src/app/integrations/landing-v2/landing-v2.component.scss
  src/app/integrations/landing-v2/landing-v2.component.ts
  src/app/shared/components/core/badge/badge.component.scss
  src/assets/logos/bamboo-hr-logo.png
  src/assets/logos/intacct-logo-new.png
  src/assets/logos/netsuite-logo-new.png
  src/assets/logos/sage300-logo.png
  src/assets/logos/travelperk-logo.png
  src/assets/logos/xero-logo-new.png
Labels: size/L

#1140 feat: new app tile structure + remove extra content
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/integrations/integrations.model.ts
  src/app/core/services/common/integrations.service.spec.ts
  src/app/core/services/common/integrations.service.ts
  src/app/integrations/integrations-routing.module.ts
  src/app/integrations/landing-v2/landing-v2.component.html
  src/app/integrations/landing-v2/landing-v2.component.scss
  src/app/integrations/landing-v2/landing-v2.component.ts
  src/app/shared/components/core/badge/badge.component.scss
  src/assets/logos/bamboo-hr-logo.png
  src/assets/logos/intacct-logo-new.png
  src/assets/logos/netsuite-logo-new.png
  src/assets/logos/sage300-logo.png
  src/assets/logos/travelperk-logo.png
  src/assets/logos/xero-logo-new.png
Labels: size/L

#1139 feat: create new landing page and add header and tab switcher
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/integrations/integrations.model.ts
  src/app/core/services/common/integrations.service.spec.ts
  src/app/core/services/common/integrations.service.ts
  src/app/integrations/integrations-routing.module.ts
  src/app/integrations/integrations.module.ts
  src/app/integrations/landing-v2/landing-v2.component.html
  src/app/integrations/landing-v2/landing-v2.component.scss
  src/app/integrations/landing-v2/landing-v2.component.spec.ts
  src/app/integrations/landing-v2/landing-v2.component.ts
  src/app/shared/components/core/badge/badge.component.scss
  src/assets/logos/bamboo-hr-logo.png
  src/assets/logos/intacct-logo-new.png
  src/assets/logos/netsuite-logo-new.png
  src/assets/logos/sage300-logo.png
  src/assets/logos/travelperk-logo.png
  src/assets/logos/xero-logo-new.png
Labels: size/L

#1151 feat: new integrations landing page (`/landing_v2`)
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/integrations/integrations.model.ts
  src/app/core/services/common/integrations.service.spec.ts
  src/app/core/services/common/integrations.service.ts
  src/app/integrations/integrations-routing.module.ts
  src/app/integrations/integrations.module.ts
  src/app/integrations/landing-v2/landing-v2.component.html
  src/app/integrations/landing-v2/landing-v2.component.scss
  src/app/integrations/landing-v2/landing-v2.component.spec.ts
  src/app/integrations/landing-v2/landing-v2.component.ts
  src/app/shared/components/core/badge/badge.component.scss
  src/assets/logos/bamboo-hr-logo.png
  src/assets/logos/intacct-logo-new.png
  src/assets/logos/netsuite-logo-new.png
  src/assets/logos/sage300-logo.png
  src/assets/logos/travelperk-logo.png
  src/assets/logos/xero-logo-new.png
Labels: size/L

#1152 fix: Critical issues
  package-lock.json
  package.json
Labels: deploy, size/XL

#1155 fix: qbd direct connection phase fix
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.ts
Labels: size/XS

#1154 feat: white lableing - converting all fyle reference to generic form
  src/app/branding/c1-contents-config.ts
  src/app/branding/fyle-contents-config.ts
  src/app/core/models/branding/content-configuration.model.ts
  src/app/core/models/xero/xero-configuration/xero-advanced-settings.model.ts
  src/app/core/models/xero/xero-configuration/xero-export-settings.model.ts
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.html
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-completed-export-log/intacct-completed-export-log.component.html
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-completed-export-log/intacct-completed-export-log.component.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-skip-export-log/intacct-skip-export-log.component.html
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-skip-export-log/intacct-skip-export-log.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
  src/app/integrations/netsuite/netsuite-main/netsuite-dashboard/netsuite-dashboard.component.html
  src/app/integrations/netsuite/netsuite-main/netsuite-dashboard/netsuite-dashboard.component.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-export-log/netsuite-complete-export-logs/netsuite-complete-export-logs.component.html
  src/app/integrations/netsuite/netsuite-main/netsuite-export-log/netsuite-complete-export-logs/netsuite-complete-export-logs.component.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-export-log/netsuite-skipped-export-log/netsuite-skipped-export-log.component.html
  src/app/integrations/netsuite/netsuite-main/netsuite-export-log/netsuite-skipped-export-log/netsuite-skipped-export-log.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-complete-export-log/qbd-direct-complete-export-log.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-complete-export-log/qbd-direct-complete-export-log.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-skipped-export-log/qbd-direct-skipped-export-log.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-skipped-export-log/qbd-direct-skipped-export-log.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-landing/qbd-direct-onboarding-landing.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-setup-connection/qbd-direct-setup-connection.component.html
  src/app/integrations/qbo/qbo-main/qbo-dashboard/qbo-dashboard.component.html
  src/app/integrations/qbo/qbo-main/qbo-dashboard/qbo-dashboard.component.ts
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-complete-export-log/qbo-complete-export-log.component.html
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-complete-export-log/qbo-complete-export-log.component.ts
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-skipped-export-log/qbo-skipped-export-log.component.html
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-skipped-export-log/qbo-skipped-export-log.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-advanced-settings/qbo-advanced-settings.component.html
  src/app/integrations/sage300/sage300-shared/sage300-advanced-settings/sage300-advanced-settings.component.html
  src/app/integrations/xero/xero-main/xero-dashboard/xero-dashboard.component.html
  src/app/integrations/xero/xero-main/xero-dashboard/xero-dashboard.component.ts
  src/app/integrations/xero/xero-main/xero-export-log/xero-complete-export-log/xero-complete-export-log.component.html
  src/app/integrations/xero/xero-main/xero-export-log/xero-complete-export-log/xero-complete-export-log.component.ts
  src/app/integrations/xero/xero-main/xero-export-log/xero-skipped-export-log/xero-skipped-export-log.component.html
  src/app/integrations/xero/xero-main/xero-export-log/xero-skipped-export-log/xero-skipped-export-log.component.ts
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.html
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.ts
  src/app/shared/components/helper/mapping/mapping-filter/mapping-filter.component.ts
Labels: size/L

#1159 fix: qbd direct advanced settings post onboarding fix
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.html
Labels: size/XS

#1160 fix: Successful export dialog view
  .github/workflows/unit-test.yml
  package-lock.json
  src/app/core/models/common/export-settings.model.ts
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
  src/app/integrations/sage300/sage300-shared/sage300-export-settings/sage300-export-settings.component.ts
  src/app/integrations/xero/xero-shared/xero-export-settings/xero-export-settings.component.ts
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.ts
Labels: deploy, size/XL

#1162 feat: only show top level when multiple location entity
  src/app/shared/components/si/core/intacct-location-entity/intacct-location-entity.component.ts
Labels: size/XS

#1165 fix: employee mapping field not populating on page load
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.ts
Labels: deploy, size/XS

#1164 feat: common main pages shadow style conversion
  src/app/branding/c1-style-config.ts
  src/app/branding/fyle-style-config.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-completed-export-log/intacct-completed-export-log.component.html
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-completed-export-log/intacct-completed-export-log.component.ts
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-skip-export-log/intacct-skip-export-log.component.html
  src/app/integrations/intacct/intacct-main/intacct-export-log/intacct-skip-export-log/intacct-skip-export-log.component.ts
  src/app/integrations/landing/landing.component.html
  src/app/integrations/landing/landing.component.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-export-log/netsuite-complete-export-logs/netsuite-complete-export-logs.component.html
  src/app/integrations/netsuite/netsuite-main/netsuite-export-log/netsuite-complete-export-logs/netsuite-complete-export-logs.component.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-export-log/netsuite-skipped-export-log/netsuite-skipped-export-log.component.html
  src/app/integrations/netsuite/netsuite-main/netsuite-export-log/netsuite-skipped-export-log/netsuite-skipped-export-log.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-complete-export-log/qbd-direct-complete-export-log.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-complete-export-log/qbd-direct-complete-export-log.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-skipped-export-log/qbd-direct-skipped-export-log.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-skipped-export-log/qbd-direct-skipped-export-log.component.ts
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-complete-export-log/qbo-complete-export-log.component.html
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-complete-export-log/qbo-complete-export-log.component.ts
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-skipped-export-log/qbo-skipped-export-log.component.html
  src/app/integrations/qbo/qbo-main/qbo-export-log/qbo-skipped-export-log/qbo-skipped-export-log.component.ts
  src/app/integrations/xero/xero-main/xero-export-log/xero-complete-export-log/xero-complete-export-log.component.html
  src/app/integrations/xero/xero-main/xero-export-log/xero-complete-export-log/xero-complete-export-log.component.ts
  src/app/integrations/xero/xero-main/xero-export-log/xero-skipped-export-log/xero-skipped-export-log.component.html
  src/app/integrations/xero/xero-main/xero-export-log/xero-skipped-export-log/xero-skipped-export-log.component.ts
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.html
  src/app/shared/components/dashboard/dashboard-export-section/dashboard-export-section.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.html
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.html
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.ts
  src/app/shared/components/helper/mapping/mapping-card-header/mapping-card-header.component.html
  src/app/shared/components/helper/mapping/mapping-card-header/mapping-card-header.component.ts
  src/app/shared/components/helper/onboarding-done/onboarding-done.component.html
  src/app/shared/components/helper/onboarding-done/onboarding-done.component.ts
Labels: size/M

#1168 feat: qbd direct survey update for onboarding done and export done
  run.sh
  scripts/setup_env.js
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-done/qbd-direct-onboarding-done.component.ts
Labels: size/S
