Repository fylein/fyle-integrations-app, pull requests merged in 2025-03, with the labels that each got.

#1195 fix: Article links
  .github/workflows/codecov.yml
  src/app/branding/c1-branding-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/core/models/branding/kb-article.model.ts
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-mapping.component.spec.ts
  src/app/integrations/qbd/qbd.fixture.ts
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.spec.ts
  src/app/integrations/qbo/qbo.fixture.ts
Labels: deploy, size/M

#1183 feat: add a dropdown menu to the main menu for navigation and disconnection
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/branding/c1-branding-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/core/models/branding/feature-configuration.model.ts
  src/app/core/models/integrations/integrations.model.ts
  src/app/core/models/misc/main-menu-dropdown-options.ts
  src/app/core/services/business-central/business-central-configuration/business-central-connector.service.ts
  src/app/core/services/business-central/business-central-configuration/business-central-export-settings.service.ts
  src/app/core/services/business-central/business-central-configuration/business-central-import-settings.service.ts
  src/app/core/services/common/accounting-export.service.ts
  src/app/core/services/common/clone-setting.service.ts
  src/app/core/services/common/dashboard.service.ts
  src/app/core/services/common/export-log.service.ts
  src/app/core/services/common/integrations.service.ts
  src/app/core/services/common/mapping.service.ts
  src/app/core/services/netsuite/netsuite-configuration/netsuite-import-settings.service.ts
  src/app/core/services/qbd-direct/qbd-direct-configuration/qbd-direct-import-settings.service.ts
  src/app/core/services/qbo/qbo-configuration/qbo-connector.service.ts
  src/app/core/services/qbo/qbo-configuration/qbo-import-settings.service.ts
  src/app/core/services/si/export-log/export-log.service.ts
  src/app/core/services/si/si-core/dashboard.service.ts
  src/app/core/services/travelperk/travelperk.service.ts
  src/app/core/services/xero/xero-configuration/xero-connector.service.ts
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-mapping.component.spec.ts
  src/app/integrations/landing-v2/landing-v2.component.ts
  src/app/shared/components/menu/main-menu/main-menu.component.html
  src/app/shared/components/menu/main-menu/main-menu.component.scss
  src/app/shared/components/menu/main-menu/main-menu.component.ts
  src/styles.scss
Labels: size/L

#1200 fix: Fix Xero clone settings save()
  src/app/core/models/xero/xero-configuration/clone-setting.model.ts
  src/app/core/models/xero/xero-configuration/xero-advanced-settings.model.ts
  src/app/core/models/xero/xero-configuration/xero-export-settings.model.ts
  src/app/core/models/xero/xero-configuration/xero-import-settings.model.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-clone-settings/qbo-clone-settings.component.html
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.html
Labels: size/M

#1202 chore: Bring back appcues
  .gitignore
  package.json
  src/app/app.component.ts
  src/app/core/services/integration/appcues.service.spec.ts
  src/app/core/services/integration/appcues.service.ts
  src/app/integrations/intacct/intacct.component.spec.ts
  src/app/integrations/intacct/intacct.component.ts
  src/app/integrations/qbd-direct/qbd-direct.component.ts
  src/index.html
Labels: size/M

#1203 fix: outdated packages
  .github/workflows/lint.yml
  .github/workflows/unit-test.yml
  package-lock.json
  package.json
Labels: deploy, size/XL

#1205 feat: log in to all connected apps on integrations page load (wip)
  src/app/app.component.ts
  src/app/auth/login/login.component.ts
  src/app/branding/c1-branding-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/core/models/branding/feature-configuration.model.ts
  src/app/core/models/integrations/integrations.model.ts
  src/app/core/models/misc/integration-tokens-map.ts
  src/app/core/services/common/auth.service.ts
  src/app/core/services/misc/redirect-uri-storage.service.spec.ts
  src/app/core/services/misc/redirect-uri-storage.service.ts
  src/app/integrations/bamboo-hr/bamboo-hr.component.ts
  src/app/integrations/business-central/business-central.component.ts
  src/app/integrations/intacct/intacct.component.ts
  src/app/integrations/netsuite/netsuite.component.ts
  src/app/integrations/qbd-direct/qbd-direct.component.ts
  src/app/integrations/qbd/qbd.component.ts
  src/app/integrations/qbo/qbo.component.ts
  src/app/integrations/travelperk/travelperk.component.ts
  src/app/integrations/xero/xero.component.ts
  src/app/shared/components/menu/main-menu/main-menu.component.ts
Labels: deploy, qa_deploy, size/L

#1201 fix: back button navigation
  src/app/app.component.ts
  src/app/auth/login/login.component.ts
  src/app/branding/c1-branding-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/core/models/branding/feature-configuration.model.ts
  src/app/core/models/integrations/integrations.model.ts
  src/app/core/models/misc/integration-tokens-map.ts
  src/app/core/services/common/auth.service.ts
  src/app/core/services/common/events.service.ts
  src/app/core/services/misc/redirect-uri-storage.service.spec.ts
  src/app/core/services/misc/redirect-uri-storage.service.ts
  src/app/core/services/org/org.service.ts
  src/app/integrations/bamboo-hr/bamboo-hr.component.ts
  src/app/integrations/business-central/business-central.component.ts
  src/app/integrations/intacct/intacct.component.spec.ts
  src/app/integrations/intacct/intacct.component.ts
  src/app/integrations/netsuite/netsuite.component.ts
  src/app/integrations/qbd-direct/qbd-direct.component.ts
  src/app/integrations/qbd/qbd.component.ts
  src/app/integrations/qbo/qbo.component.spec.ts
  src/app/integrations/qbo/qbo.component.ts
  src/app/integrations/travelperk/travelperk.component.ts
  src/app/integrations/xero/xero.component.ts
  src/app/shared/components/menu/main-menu/main-menu.component.ts
Labels: deploy, size/L

#1206 fix: restore the original functionality of `native_apps`
  src/app/app.component.ts
  src/app/auth/login/login.component.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/services/common/auth.service.ts
  src/app/core/services/misc/iframe-origin-storage.service.spec.ts
  src/app/core/services/misc/iframe-origin-storage.service.ts
  src/app/shared/components/menu/main-menu/main-menu.component.html
  src/app/shared/components/menu/main-menu/main-menu.component.ts
Labels: size/M

#1207 fix: move login event handlers from app to login component
  src/app/app.component.ts
  src/app/auth/login/login.component.ts
Labels: size/M

#1209 fix: hide QBD IIF integration for newer orgs
  src/app/integrations/landing-v2/landing-v2.component.ts
Labels: size/XS

#1210 fix: incorrect base API urls on page refresh
  src/app/core/services/common/api.service.ts
  src/app/core/services/common/integrations.service.ts
Labels: deploy, size/XS

#1213 fix: update QBO Journal Entry preview screenshots
  src/assets/pngs/preview-screens/qbo-ccc-journal-entry.png
  src/assets/pngs/preview-screens/qbo-reimburse-journal-entry.png
Labels: deploy, size/XS

#1208 fix: add field options missing from the paginated GET call
  src/app/core/services/common/helper.service.ts
  src/app/core/services/common/mapping.service.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.ts
Labels: deploy, size/M

#1214 Feat: Minor content change for Capital One
  src/app/branding/branding-config.ts
  src/app/branding/c1-content-config.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-import-settings/netsuite-custom-segment-dialog/netsuite-custom-segment-dialog.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-complete-export-log/qbd-direct-complete-export-log.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-export-log.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-mapping.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.ts
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.ts
Labels: size/S

#1215 fix: polling for QBO
  src/app/integrations/qbo/qbo-main/qbo-dashboard/qbo-dashboard.component.ts
Labels: size/XS

#1217 fix: logo and button width for all screen sizes
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
Labels: size/XS

#1221 fix: netsuite custom segment dialog placeholder
  src/app/integrations/netsuite/netsuite-shared/netsuite-import-settings/netsuite-custom-segment-dialog/netsuite-custom-segment-dialog.component.html
Labels: size/XS

#1218 fix: remove 'Connect' text on BC tile hover
  src/app/integrations/landing-v2/landing-v2.component.html
Labels: size/XS

#1212 feat: track new landing_v2 features
  src/app/core/services/integration/tracking.service.ts
  src/app/integrations/landing-v2/landing-v2.component.ts
  src/app/shared/components/menu/main-menu/main-menu.component.html
  src/app/shared/components/menu/main-menu/main-menu.component.ts
  src/index.html
Labels: deploy, size/S

#1224 Fix: ensured correct polling behavior across all integrations
  src/app/integrations/business-central/business-central-main/business-central-dashboard/business-central-dashboard.component.ts
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-dashboard/netsuite-dashboard.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
  src/app/integrations/qbd/qbd-main/qbd-dashboard/qbd-dashboard.component.ts
  src/app/integrations/sage300/sage300-main/sage300-dashboard/sage300-dashboard.component.ts
  src/app/integrations/xero/xero-main/xero-dashboard/xero-dashboard.component.ts
Labels: size/M

#1228 feat: bamboo HR token health check.
  src/app/core/services/bamboo-hr/bamboo-hr.service.ts
  src/app/integrations/bamboo-hr/bamboo-hr.component.ts
Labels: size/S

#1230 test: unit test display name logic
  package-lock.json
  package.json
  src/app/core/services/common/common-resources.service.spec.ts
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-base-mapping/intacct-base-mapping.component.spec.ts
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-mapping.component.spec.ts
  src/app/integrations/intacct/intacct.fixture.ts
Labels: size/M

#1227 feat: replace all dimension names with display names
  package-lock.json
  package.json
  src/app/core/services/common/common-resources.service.spec.ts
  src/app/core/services/common/common-resources.service.ts
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-base-mapping/intacct-base-mapping.component.html
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-base-mapping/intacct-base-mapping.component.spec.ts
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-base-mapping/intacct-base-mapping.component.ts
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-mapping.component.spec.ts
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-mapping.component.ts
  src/app/integrations/intacct/intacct.fixture.ts
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.html
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.ts
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.html
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.ts
  src/app/shared/components/helper/mapping/mapping-card-header/mapping-card-header.component.html
  src/app/shared/components/helper/mapping/mapping-card-header/mapping-card-header.component.ts
Labels: deploy, size/M

#1225 fix: Run container with non root user
  Dockerfile
Labels: size/XS

#1232 fix: Revert "fix: Run container with non root user (#1225)"
  Dockerfile
Labels: size/XS

#1237 fix: article links in qbd direct
  src/app/branding/fyle-branding-config.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.ts
Labels: size/XS

#1236 fix: users being redirected to qbd direct landing after onboarding
  src/app/branding/fyle-branding-config.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-landing/qbd-direct-onboarding-landing.component.ts
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.ts
Labels: size/S

#1233 fix: Run container with non root user - 1
  Dockerfile
  nginx.conf
Labels: deploy, size/S
