Repository fylein/fyle-integrations-app, pull requests merged in 2025-09, with the labels that each got.

#1495 feat: migrate remaining edge-case config dropdowns
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/input/dropdown/dropdown.component.ts
Labels: size/S

#1493 feat: migrate qbd schedule export dropdowns
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/input/dropdown/dropdown.component.html
  src/app/shared/components/input/dropdown/dropdown.component.ts
  src/app/shared/components/onboarding/clone-setting/clone-setting-field/clone-setting-field.component.html
Labels: size/M

#1500 fix: landing header copy across all integrations
  src/assets/i18n/en.json
  src/assets/i18n/fyle/en.json
Labels: size/XS

#1507 feat: implement sage50 auth
  src/app/app.component.ts
  src/app/auth/login/login.component.ts
  src/app/branding/c1/branding-config.ts
  src/app/branding/expose-app-config.ts
  src/app/branding/fyle/branding-config.ts
  src/app/core/models/branding/demo-video.model.ts
  src/app/core/models/branding/expose-app-configuration.model.ts
  src/app/core/models/branding/kb-article.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/integrations/integrations.model.ts
  src/app/core/models/misc/onboarding-stepper.model.ts
  src/app/core/models/misc/tracking.model.ts
  src/app/core/services/common/helper.service.ts
  src/app/core/services/common/integrations.service.ts
  src/app/core/services/sage50/sage50-configuration/sage50-onboarding.service.ts
  src/app/integrations/landing-v2/landing-v2.component.html
  src/app/integrations/landing-v2/landing-v2.component.ts
  src/app/integrations/landing/landing.component.ts
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-landing/sage50-onboarding-landing.component.html
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-landing/sage50-onboarding-landing.component.scss
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-landing/sage50-onboarding-landing.component.ts
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.html
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.scss
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.ts
  src/app/integrations/sage50/sage50-routing.ts
  src/app/integrations/sage50/sage50.component.ts
  src/app/shared/components/configuration/configuration-step-header/configuration-step-header.component.html
  src/app/shared/components/configuration/configuration-step-header/configuration-step-header.component.ts
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.ts
  src/assets/flow-charts/sage50-flow-chart.svg
  src/assets/i18n/en.json
  src/assets/icons/info-circle-fill-blue.svg
  src/assets/logos/sage50-logo.svg
Labels: size/L

#1506 feat: setup the base sage50 component
  .cursor/rules/code-changes.mdc
  .cursor/rules/component-creation.mdc
  .github/workflows/unit-test.yml
  run.sh
  scripts/setup_env.js
  src/app/app.component.ts
  src/app/auth/login/login.component.ts
  src/app/branding/c1/branding-config.ts
  src/app/branding/expose-app-config.ts
  src/app/branding/fyle/branding-config.ts
  src/app/core/models/branding/demo-video.model.ts
  src/app/core/models/branding/expose-app-configuration.model.ts
  src/app/core/models/branding/kb-article.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/integrations/integrations.model.ts
  src/app/core/models/misc/onboarding-stepper.model.ts
  src/app/core/models/misc/tracking.model.ts
  src/app/core/models/sage50/db/sage50-workspace.model.ts
  src/app/core/services/common/helper.service.ts
  src/app/core/services/common/integrations.service.ts
  src/app/core/services/common/workspace.service.ts
  src/app/core/services/sage50/sage50-configuration/sage50-onboarding.service.ts
  src/app/integrations/integrations-routing.module.ts
  src/app/integrations/landing-v2/landing-v2.component.html
  src/app/integrations/landing-v2/landing-v2.component.ts
  src/app/integrations/landing/landing.component.ts
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-landing/sage50-onboarding-landing.component.html
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-landing/sage50-onboarding-landing.component.scss
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-landing/sage50-onboarding-landing.component.ts
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.html
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.scss
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.ts
  src/app/integrations/sage50/sage50-routing.ts
  src/app/integrations/sage50/sage50.component.html
  src/app/integrations/sage50/sage50.component.scss
  src/app/integrations/sage50/sage50.component.ts
  src/app/shared/components/configuration/configuration-step-header/configuration-step-header.component.html
  src/app/shared/components/configuration/configuration-step-header/configuration-step-header.component.ts
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.ts
  src/assets/flow-charts/sage50-flow-chart.svg
  src/assets/i18n/en.json
  src/assets/icons/info-circle-fill-blue.svg
  src/assets/logos/sage50-logo.svg
Labels: size/L

#1518 fix: quickbooks token expired page header text
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.html
Labels: size/XS

#1517 fix: QBD mapping advanced search logic
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-mapping.service.spec.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-mapping.service.ts
  src/app/core/services/qbd-direct/qbd-direct-core/qbd-direct-mappings.service.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-base-mapping/qbd-direct-base-mapping.component.ts
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.ts
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.html
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.ts
Labels: staging_deploy, size/L

#1515 feat: CSV upload button UI
  src/app/branding/c1/style-config.ts
  src/app/branding/fyle/style-config.ts
  src/app/core/models/enum/enum.model.ts
  src/app/shared/components/configuration/configuration-csv-upload-field/configuration-csv-upload-field.component.html
  src/app/shared/components/configuration/configuration-csv-upload-field/configuration-csv-upload-field.component.ts
  src/app/shared/components/input/csv-upload-button/csv-upload-button.component.html
  src/app/shared/components/input/csv-upload-button/csv-upload-button.component.scss
  src/app/shared/components/input/csv-upload-button/csv-upload-button.component.ts
  src/assets/i18n/en.json
  src/assets/icons/file-csv-dark.svg
Labels: size/M

#1514 feat: fetch file names, implement data flow
  src/app/branding/c1/style-config.ts
  src/app/branding/fyle/style-config.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/sage50/db/sage50-import-attributes.model.ts
  src/app/core/services/sage50/sage50-configuration/sage50-import-attributes.service.ts
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.html
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.ts
  src/app/shared/components/configuration/configuration-csv-upload-field/configuration-csv-upload-field.component.html
  src/app/shared/components/configuration/configuration-csv-upload-field/configuration-csv-upload-field.component.ts
  src/app/shared/components/input/csv-upload-button/csv-upload-button.component.html
  src/app/shared/components/input/csv-upload-button/csv-upload-button.component.scss
  src/app/shared/components/input/csv-upload-button/csv-upload-button.component.ts
  src/assets/i18n/en.json
  src/assets/icons/file-csv-dark.svg
Labels: size/L

#1513 feat: configuration CSV upload field UI
  src/app/branding/c1/style-config.ts
  src/app/branding/fyle/style-config.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/sage50/db/sage50-import-attributes.model.ts
  src/app/core/services/sage50/sage50-configuration/sage50-import-attributes.service.ts
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.html
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.ts
  src/app/shared/components/configuration/configuration-csv-upload-field/configuration-csv-upload-field.component.html
  src/app/shared/components/configuration/configuration-csv-upload-field/configuration-csv-upload-field.component.scss
  src/app/shared/components/configuration/configuration-csv-upload-field/configuration-csv-upload-field.component.ts
  src/app/shared/components/configuration/configuration-step-header/configuration-step-header.component.html
  src/app/shared/components/core/svg-icon/svg-icon.component.html
  src/app/shared/components/core/svg-icon/svg-icon.component.ts
  src/app/shared/components/input/button/button.component.html
  src/app/shared/components/input/button/button.component.ts
  src/app/shared/components/input/csv-upload-button/csv-upload-button.component.html
  src/app/shared/components/input/csv-upload-button/csv-upload-button.component.scss
  src/app/shared/components/input/csv-upload-button/csv-upload-button.component.ts
  src/assets/i18n/en.json
  src/assets/icons/file-csv-dark.svg
  src/assets/icons/file-csv.svg
Labels: size/L

#1527 fix: netsuite export settings, for CCC on BILL save button disabled
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.ts
Labels: staging_deploy, size/XS

#1531 fix: qbo import settings transloco content
  src/app/integrations/qbo/qbo-shared/qbo-import-settings/qbo-import-settings.component.html
Labels: size/XS

#1530 fix: advanced settings multiselect field order by original group & card number last 4 digit content change
  src/app/shared/components/configuration/configuration-multi-select/configuration-multi-select.component.ts
  src/assets/i18n/en.json
Labels: size/S

#1528 feat: call `/import_attributes` & handle response
  .github/workflows/unit-test.yml
  src/app/core/models/common/csv-error.model.ts
  src/app/core/models/db/csv-import-attributes.model.ts
  src/app/core/models/sage50/db/sage50-import-attributes.model.ts
  src/app/core/services/common/csv-json-translator.service.ts
  src/app/core/services/sage50/sage50-configuration/sage50-import-attributes.service.ts
  src/app/core/util/downloadFile.ts
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.html
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.ts
  src/app/shared/components/configuration/configuration-csv-upload-field/configuration-csv-upload-field.component.ts
  src/app/shared/components/dialog/csv-upload-dialog/csv-upload-dialog.component.ts
  src/assets/i18n/en.json
Labels: size/M

#1524 feat: native file picker + drag-n-drop
  .github/workflows/unit-test.yml
  package-lock.json
  package.json
  src/app/core/models/common/csv-error.model.ts
  src/app/core/models/db/csv-import-attributes.model.ts
  src/app/core/models/sage50/db/sage50-import-attributes.model.ts
  src/app/core/services/common/csv-json-translator.service.ts
  src/app/core/services/sage50/sage50-configuration/sage50-import-attributes.service.ts
  src/app/core/util/downloadFile.ts
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.html
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.ts
  src/app/shared/components/configuration/configuration-csv-upload-field/configuration-csv-upload-field.component.ts
  src/app/shared/components/core/dialog/dialog.component.html
  src/app/shared/components/core/dialog/dialog.component.scss
  src/app/shared/components/core/dialog/dialog.component.ts
  src/app/shared/components/core/dynamic-dialog/dynamic-dialog.component.html
  src/app/shared/components/core/dynamic-dialog/dynamic-dialog.component.scss
  src/app/shared/components/core/dynamic-dialog/dynamic-dialog.component.ts
  src/app/shared/components/dialog/csv-upload-dialog/csv-upload-dialog.component.html
  src/app/shared/components/dialog/csv-upload-dialog/csv-upload-dialog.component.scss
  src/app/shared/components/dialog/csv-upload-dialog/csv-upload-dialog.component.ts
  src/assets/i18n/en.json
Labels: size/L

#1522 feat: loading and error states in CSV dialog
  .github/workflows/unit-test.yml
  package-lock.json
  package.json
  src/app/branding/fyle/style-config.ts
  src/app/core/models/common/csv-error.model.ts
  src/app/core/models/db/csv-import-attributes.model.ts
  src/app/core/models/sage50/db/sage50-import-attributes.model.ts
  src/app/core/services/common/csv-json-translator.service.ts
  src/app/core/services/sage50/sage50-configuration/sage50-import-attributes.service.ts
  src/app/core/util/downloadFile.ts
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.html
  src/app/integrations/sage50/sage50-onboarding/sage50-onboarding-prerequisites/sage50-onboarding-prerequisites.component.ts
  src/app/shared/components/configuration/configuration-csv-upload-field/configuration-csv-upload-field.component.ts
  src/app/shared/components/core/dialog/dialog.component.html
  src/app/shared/components/core/dialog/dialog.component.scss
  src/app/shared/components/core/dialog/dialog.component.ts
  src/app/shared/components/core/dynamic-dialog/dynamic-dialog.component.html
  src/app/shared/components/core/dynamic-dialog/dynamic-dialog.component.scss
  src/app/shared/components/core/dynamic-dialog/dynamic-dialog.component.ts
  src/app/shared/components/dialog/csv-upload-dialog/csv-upload-dialog.component.html
  src/app/shared/components/dialog/csv-upload-dialog/csv-upload-dialog.component.scss
  src/app/shared/components/dialog/csv-upload-dialog/csv-upload-dialog.component.ts
  src/assets/i18n/en.json
Labels: size/L
