Repository fylein/fyle-integrations-app, pull requests merged in 2025-05, with the labels that each got.

#1287 fix: clear old tokens before login
  src/app/auth/login/login.component.ts
  src/app/core/services/common/auth.service.ts
Labels: deploy

#1288 fix: prevent redirection when navigating to the current integration
  src/app/shared/components/menu/main-menu/main-menu.component.ts
Labels: size/XS

#1290 feat: add global action for outdated-js-scan and eol-scan
  .github/workflows/eol-outdated-js-scan.yml
  .github/workflows/jscpd-duplication-check.yml
Labels: size/M

#1292 fix: required fields missing validators
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
Labels: size/XS

#1293 fix: add validators for required fields in all apps
  src/app/core/services/common/helper.service.ts
Labels: size/S

#1297 fix: send `app_name` in Sage 300 > `/expense_attributes` payload
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.ts
Labels: deploy, size/XS

#1301 fix: send `app_name` in Sage 300 mapping filter payload
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.ts
Labels: deploy, size/XS

#1294 feat: introduce real-time export option in advanced setting
  src/app/core/models/xero/xero-configuration/xero-advanced-settings.model.ts
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.ts
  src/app/integrations/xero/xero-shared/xero-advanced-settings/xero-advanced-settings.component.ts
  src/app/shared/components/configuration/configuration-schedule-export/configuration-schedule-export.component.html
  src/app/shared/components/configuration/configuration-schedule-export/configuration-schedule-export.component.scss
  src/app/shared/components/configuration/configuration-schedule-export/configuration-schedule-export.component.ts
  src/app/shared/components/input/dropdown/dropdown.component.scss
  tailwind.config.js
Labels: size/M

#1299 chore: ignore config & unused files in the jscpd workflow
  .github/workflows/jscpd-duplication-check.yml
Labels: size/XS

#1296 refactor: delete unused xero skip export page
  .github/workflows/jscpd-duplication-check.yml
  src/app/integrations/xero/xero-main/xero-export-log/xero-export-log-routing.module.ts
  src/app/integrations/xero/xero-main/xero-export-log/xero-skipped-export-log/xero-skipped-export-log.component.html
  src/app/integrations/xero/xero-main/xero-export-log/xero-skipped-export-log/xero-skipped-export-log.component.scss
  src/app/integrations/xero/xero-main/xero-export-log/xero-skipped-export-log/xero-skipped-export-log.component.spec.ts
  src/app/integrations/xero/xero-main/xero-export-log/xero-skipped-export-log/xero-skipped-export-log.component.ts
  src/app/integrations/xero/xero-main/xero-main.module.ts
Labels: size/M

#1303 fix: JSCPD coderabbit comment bugfix + duplication % diff
  .github/workflows/jscpd-duplication-check.yml
Labels: size/XS

#1307 fix: typo in xero token guard redirection
  src/app/core/guard/xero-token.guard.ts
Labels: size/XS

#1306 fix: update column name for Intacct CC -> vendor mapping
  src/app/core/models/enum/enum.model.ts
  src/app/integrations/intacct/intacct-main/intacct-mapping/intacct-base-mapping/intacct-base-mapping.component.ts
Labels: size/XS

#1305 feat: Set real-time export as default enabled for new onboarding orgs
  src/app/core/models/xero/xero-configuration/xero-advanced-settings.model.ts
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.ts
  src/app/integrations/xero/xero-shared/xero-advanced-settings/xero-advanced-settings.component.ts
Labels: size/XS

#1300 feat: Je Single Line Item
  src/app/core/models/db/configuration.model.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/intacct/db/configuration.model.ts
  src/app/core/models/intacct/intacct-configuration/advanced-settings.model.ts
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-advanced-settings/intacct-advanced-settings.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.ts
  src/app/integrations/intacct/intacct.fixture.ts
Labels: size/M

#1308 fix: navigation by url to sub-pages
  src/app/integrations/business-central/business-central-main/business-central-main-routing.module.ts
  src/app/integrations/business-central/business-central-main/business-central-main.component.ts
  src/app/integrations/intacct/intacct-main/intacct-main-routing.module.ts
  src/app/integrations/intacct/intacct-main/intacct-main.component.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-main-routing.module.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-main.component.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-main-routing.module.ts
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-main.component.ts
  src/app/integrations/qbd/qbd-main/qbd-main-routing.module.ts
  src/app/integrations/qbd/qbd-main/qbd-main.component.ts
  src/app/integrations/qbo/qbo-main/qbo-main-routing.module.ts
  src/app/integrations/qbo/qbo-main/qbo-main.component.ts
  src/app/integrations/sage300/sage300-main/sage300-main-routing.module.ts
  src/app/integrations/sage300/sage300-main/sage300-main.component.ts
  src/app/integrations/travelperk/travelperk-main/travelperk-main-routing.module.ts
  src/app/integrations/travelperk/travelperk-main/travelperk-main.component.ts
  src/app/integrations/xero/xero-main/xero-main-routing.module.ts
  src/app/integrations/xero/xero-main/xero-main.component.ts
  src/app/shared/components/menu/sub-menu/sub-menu.component.ts
Labels: deploy, size/M

#1310 fix: send `app_name` in all mapping page request payloads
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.ts
Labels: deploy, size/XS

#1311 feat: Real-time exports, phase 2 - QBO
  src/app/core/models/common/advanced-settings.model.ts
  src/app/core/models/qbo/qbo-configuration/qbo-advanced-setting.model.ts
  src/app/core/services/common/accounting-export.service.ts
  src/app/core/services/common/export-log.service.ts
  src/app/integrations/qbo/qbo-main/qbo-dashboard/qbo-dashboard.component.ts
  src/app/integrations/qbo/qbo-onboarding/qbo-clone-settings/qbo-clone-settings.component.ts
  src/app/integrations/qbo/qbo-shared/qbo-advanced-settings/qbo-advanced-settings.component.ts
  src/app/integrations/qbo/qbo.fixture.ts
  src/app/integrations/xero/xero-main/xero-dashboard/xero-dashboard.component.ts
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.ts
  src/app/integrations/xero/xero-shared/xero-advanced-settings/xero-advanced-settings.component.ts
  src/app/shared/components/configuration/configuration-schedule-export/configuration-schedule-export.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.ts
Labels: size/M

#1312 feat: Real-time exports, phase 2 - NetSuite
  README.md
  src/app/core/models/netsuite/netsuite-configuration/netsuite-advanced-settings.model.ts
  src/app/core/services/common/accounting-export.service.ts
  src/app/core/services/common/export-log.service.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-dashboard/netsuite-dashboard.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-advanced-settings/netsuite-advanced-settings.component.ts
  src/app/shared/components/configuration/configuration-schedule-export/configuration-schedule-export.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.html
  src/app/shared/components/dashboard/dashboard-export-summary-section/dashboard-export-summary-section.component.ts
Labels: size/M

#1316 chore: update dependencies in package.json and package-lock.json
  package-lock.json
  package.json
Labels: size/XL

#1317 fix: turn off real-time export in QBO/Xero
  src/app/core/models/qbo/qbo-configuration/qbo-advanced-setting.model.ts
  src/app/core/models/xero/xero-configuration/xero-advanced-settings.model.ts
Labels: deploy, size/XS

#1318 feat: default to landing v2 for fyle theme
  src/app/branding/c1-branding-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/core/models/branding/feature-configuration.model.ts
  src/app/integrations/integrations.component.ts
Labels: deploy, size/XS
