Repository fylein/fyle-integrations-app, pull requests merged in 2025-08, with the labels that each got.

#1402 feat: Update primary color
  src/app/branding/fyle/branding-config.ts
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.scss
  src/app/integrations/qbd/qbd-shared/qbd-advanced-setting/qbd-advanced-setting.component.html
  src/app/integrations/qbd/qbd-shared/qbd-export-setting/qbd-export-setting.component.html
  src/app/integrations/sage300/sage300-shared/sage300-export-settings/sage300-export-settings.component.html
  src/app/integrations/sage300/sage300-shared/sage300-import-settings/sage300-import-settings.component.html
  src/app/integrations/xero/xero-shared/xero-export-settings/xero-export-settings.component.html
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.scss
  src/app/shared/components/configuration/configuration-info-label/configuration-info-label.component.scss
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.scss
  src/app/shared/components/dashboard/dashboard-export-section/dashboard-export-section.component.html
  src/app/shared/components/onboarding/clone-setting/clone-setting-header/clone-setting-header.component.html
  src/assets/illustrations/dashboard-illustration.svg
  src/assets/illustrations/error.svg
  src/assets/illustrations/integrations-zero-state.svg
  src/assets/illustrations/login.svg
  src/assets/illustrations/pinktick.svg
  src/assets/illustrations/search-result-empty.svg
  src/assets/illustrations/vertical-divider.svg
  src/assets/illustrations/zero-state.svg
  src/assets/themes/fyle/fdl.scss
  src/assets/themes/fyle/primitives_variables.scss
  src/assets/themes/theme.scss
  tailwind.config.js
Labels: size/M

#1404 feat: change font from aktiv-grotesk to sage-ui
  src/assets/fonts/sage-ui-bold.otf
  src/assets/fonts/sage-ui-medium.otf
  src/assets/fonts/sage-ui-regular.otf
  src/assets/themes/theme.scss
  src/styles.scss
Labels: size/S

#1406 chore: toggle, flow chart and few more misc theme changes
  src/assets/flow-charts/bamboo-hr-flow-chart-old.svg
  src/assets/flow-charts/bamboo-hr-flow-chart.svg
  src/assets/flow-charts/fyle-netsuite-data-flow-old.svg
  src/assets/flow-charts/fyle-netsuite-data-flow.svg
  src/assets/flow-charts/fyle-qbd-direct-flow-chart-old.svg
  src/assets/flow-charts/fyle-qbd-direct-flow-chart.svg
  src/assets/flow-charts/fyle-qbo-data-flow-old.svg
  src/assets/flow-charts/fyle-qbo-data-flow.svg
  src/assets/flow-charts/fyle-sage-flow-chart-old.svg
  src/assets/flow-charts/fyle-sage-flow-chart.svg
  src/assets/flow-charts/fyle-xero-data-flow-old.svg
  src/assets/flow-charts/fyle-xero-data-flow.svg
  src/assets/flow-charts/ms-dynamics-flow-chart-old.svg
  src/assets/flow-charts/ms-dynamics-flow-chart.svg
  src/assets/flow-charts/qbd-flow-chart-old.svg
  src/assets/flow-charts/qbd-flow-chart.svg
  src/assets/flow-charts/sage300-flow-chart-old.svg
  src/assets/flow-charts/sage300-flow-chart.svg
  src/assets/flow-charts/travelperk-flow-chart-old.svg
  src/assets/flow-charts/travelperk-flow-chart.svg
  src/assets/logos/email/fyle_logo_black_full.png
  src/assets/logos/email/fyle_logo_black_full_old.png
  src/assets/themes/co/c1dl.scss
  src/assets/themes/fyle/fdl.scss
  src/assets/themes/fyle/primitives_variables.scss
  src/assets/themes/theme.scss
  src/styles.scss
  tailwind.config.js
Labels: deploy, size/XL

#1410 feat: theme sage primary buttons support
  src/app/branding/c1/branding-config.ts
  src/app/branding/c1/style-config.ts
  src/app/branding/fyle/branding-config.ts
  src/app/branding/fyle/style-config.ts
  src/app/core/models/branding/feature-configuration.model.ts
  src/app/integrations/bamboo-hr/bamboo-hr.component.html
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.html
  src/app/shared/components/configuration/configuration-step-footer/configuration-step-footer.component.html
  src/app/shared/components/configuration/configuration-step-header/configuration-step-header.component.html
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.html
  src/app/shared/components/dashboard/dashboard-export-section/dashboard-export-section.component.html
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.html
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
  src/app/shared/components/helper/mapping/mapping-card-header/mapping-card-header.component.html
  src/app/shared/components/helper/onboarding-done/onboarding-done.component.html
  src/app/shared/components/input/outlined-icon-button/outlined-icon-button.component.html
  src/app/shared/components/input/outlined-icon-button/outlined-icon-button.component.ts
  src/app/shared/components/input/primary-button/primary-button.component.html
  src/app/shared/components/input/primary-button/primary-button.component.scss
  src/app/shared/components/input/primary-button/primary-button.component.spec.ts
  src/app/shared/components/input/primary-button/primary-button.component.ts
  src/app/shared/components/menu/main-menu/main-menu.component.html
  src/app/shared/components/menu/main-menu/main-menu.component.ts
  src/app/shared/shared.module.ts
  src/assets/themes/fyle/fdl.scss
  src/assets/themes/fyle/primitives_variables.scss
  tailwind.config.js
Labels: size/L

#1408 feat: theme sage primary/secondary buttons
  src/app/branding/c1/branding-config.ts
  src/app/branding/c1/style-config.ts
  src/app/branding/fyle/branding-config.ts
  src/app/branding/fyle/style-config.ts
  src/app/core/models/branding/feature-configuration.model.ts
  src/app/integrations/bamboo-hr/bamboo-hr.component.html
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.html
  src/app/shared/components/configuration/configuration-step-footer/configuration-step-footer.component.html
  src/app/shared/components/configuration/configuration-step-header/configuration-step-header.component.html
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.html
  src/app/shared/components/dashboard/dashboard-export-section/dashboard-export-section.component.html
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.html
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
  src/app/shared/components/helper/mapping/mapping-card-header/mapping-card-header.component.html
  src/app/shared/components/helper/onboarding-done/onboarding-done.component.html
  src/app/shared/components/input/outlined-icon-button/outlined-icon-button.component.html
  src/app/shared/components/input/outlined-icon-button/outlined-icon-button.component.ts
  src/app/shared/components/input/primary-button/primary-button.component.html
  src/app/shared/components/input/primary-button/primary-button.component.scss
  src/app/shared/components/input/primary-button/primary-button.component.spec.ts
  src/app/shared/components/input/primary-button/primary-button.component.ts
  src/app/shared/components/menu/main-menu/main-menu.component.html
  src/app/shared/components/menu/main-menu/main-menu.component.ts
  src/app/shared/shared.module.ts
  src/assets/themes/fyle/fdl.scss
  src/assets/themes/fyle/primitives_variables.scss
  tailwind.config.js
Labels: size/L

#1415 fix: primary buttons sage theme misses on qbd iff
  src/app/integrations/qbd/qbd-main/qbd-dashboard/qbd-dashboard.component.html
  src/app/integrations/qbd/qbd-onboarding/qbd-onboarding-done/qbd-onboarding-done.component.html
Labels: size/XS

#1414 feat: theme sage zero state illustrations
  src/assets/illustrations/dashboard-illustration.svg
  src/assets/illustrations/error.svg
  src/assets/illustrations/integrations-zero-state.svg
  src/assets/illustrations/login.svg
  src/assets/illustrations/pinktick.svg
  src/assets/illustrations/search-result-empty.svg
  src/assets/illustrations/vertical-divider.svg
  src/assets/illustrations/zero-state.svg
Labels: size/L

#1420 chore: update expense form image
  src/assets/illustrations/sageIntacct/IntacctImportSettings.png
Labels: size/XS

#1424 fix: intacct dropdown menu alignment fix
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.scss
Labels: size/XS

#1423 feat: apply error styles across all dropdowns
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.scss
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.scss
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.scss
  src/app/integrations/netsuite/netsuite-shared/netsuite-import-settings/netsuite-custom-segment-dialog/netsuite-custom-segment-dialog.component.scss
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.scss
  src/app/integrations/qbd/qbd-shared/qbd-export-setting/qbd-export-setting.component.scss
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.scss
  src/app/shared/components/configuration/configuration-mapping-fields/configuration-mapping-fields.component.scss
  src/app/shared/components/configuration/configuration-multi-select/configuration-multi-select.component.scss
  src/app/shared/components/configuration/configuration-schedule-export/configuration-schedule-export.component.scss
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.scss
  src/app/shared/components/configuration/configuration-skip-export/configuration-skip-export.component.scss
  src/app/shared/components/configuration/configuration-text-field/configuration-text-field.component.scss
  src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.scss
  src/app/shared/components/helper/mandatory-error-message/mandatory-error-message.component.html
  src/app/shared/components/input/dropdown/dropdown.component.scss
  src/app/shared/components/netsuite/core/netsuite-connector/netsuite-connector.component.scss
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.scss
  src/assets/themes/co/c1dl.scss
  src/styles.scss
Labels: size/M

#1419 feat: rebrand dropdowns
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.scss
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.scss
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.scss
  src/app/integrations/netsuite/netsuite-shared/netsuite-import-settings/netsuite-custom-segment-dialog/netsuite-custom-segment-dialog.component.scss
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-download-file/qbd-direct-download-file.component.scss
  src/app/integrations/qbd/qbd-shared/qbd-export-setting/qbd-export-setting.component.scss
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.scss
  src/app/shared/components/configuration/configuration-mapping-fields/configuration-mapping-fields.component.scss
  src/app/shared/components/configuration/configuration-multi-select/configuration-multi-select.component.scss
  src/app/shared/components/configuration/configuration-schedule-export/configuration-schedule-export.component.scss
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.scss
  src/app/shared/components/configuration/configuration-skip-export/configuration-skip-export.component.scss
  src/app/shared/components/configuration/configuration-text-field/configuration-text-field.component.scss
  src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.scss
  src/app/shared/components/helper/mandatory-error-message/mandatory-error-message.component.html
  src/app/shared/components/input/dropdown/dropdown.component.scss
  src/app/shared/components/netsuite/core/netsuite-connector/netsuite-connector.component.scss
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.scss
  src/assets/icons/caret-large-down.svg
  src/assets/themes/co/c1dl.scss
  src/assets/themes/fyle/fdl.scss
  src/assets/themes/fyle/primitives_variables.scss
  src/styles.scss
  tailwind.config.js
Labels: deploy, size/L

#1426 fix: overextending underline in export settings link
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
Labels: size/XS

#1427 fix: tabs QA issues
  src/app/branding/c1/style-config.ts
  src/app/branding/fyle/style-config.ts
  src/app/shared/components/menu/main-menu/main-menu.component.html
  src/assets/scss/tab-primary.scss
Labels: size/S

#1429 feat: change loader spinner styling
  src/app/branding/c1/branding-config.ts
  src/app/branding/fyle/branding-config.ts
  src/app/core/models/branding/feature-configuration.model.ts
  src/app/shared/components/core/loader/loader.component.html
  src/app/shared/components/core/loader/loader.component.scss
  src/app/shared/components/core/loader/loader.component.ts
  src/assets/i18n/fyle/en.json
  src/assets/themes/fyle/fdl.scss
  src/assets/themes/fyle/primitives_variables.scss
  tailwind.config.js
Labels: size/L

#1432 fix: build issue
  Dockerfile
  package.json
Labels: deploy, size/XS

#1428 feat: rebrand text inputs & related components
  src/app/integrations/intacct/intacct-shared/intacct-export-settings/intacct-export-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.html
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.scss
  src/app/shared/components/input/search/search.component.html
  src/assets/themes/co/c1dl.scss
  src/assets/themes/fyle/fdl.scss
  src/styles.scss
  tailwind.config.js
Labels: size/S

#1434 fix: ON/OFF line heigh & progress bar border-radius
  src/app/integrations/qbd/qbd-main/qbd-dashboard/qbd-dashboard.component.scss
  src/app/shared/components/dashboard/dashboard-export-section/dashboard-export-section.component.scss
  src/styles.scss
Labels: size/XS

#1435 feat: change progress bar styling
  src/assets/themes/theme.scss
Labels: size/XS

#1439 feat: focus styles for all inputs
  src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.scss
  src/app/shared/components/input/search/search.component.html
  src/assets/themes/fyle/fdl.scss
  src/assets/themes/fyle/primitives_variables.scss
  src/styles.scss
  tailwind.config.js
Labels: size/M

#1440 fix: button fixes on bambooHR configuration page and dashboard error component
  src/app/integrations/bamboo-hr/configuration/configuration.component.html
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.html
  src/app/shared/components/input/split-menu-button/split-menu-button.component.html
Labels: size/XS

#1437 feat: theme sage p-radioButton changes
  src/assets/themes/fyle/fdl.scss
  src/assets/themes/fyle/primitives_variables.scss
  src/styles.scss
  tailwind.config.js
Labels: size/M

#1438 fix: update p-datepicker-month padding as per FDL
  src/styles.scss
Labels: size/XS

#1448 fix: journal entry name option default for c1
  src/app/core/services/netsuite/netsuite-configuration/netsuite-export-settings.service.ts
Labels: size/XS

#1446 chore: move theme.scss variables to fdl files
  src/assets/themes/co/c1dl.scss
  src/assets/themes/co/primitives_variables.scss
  src/assets/themes/fyle/fdl.scss
  src/assets/themes/fyle/primitives_variables.scss
  src/assets/themes/theme.scss
  src/styles.scss
  tailwind.config.js
Labels: size/M

#1451 fix: theme sage button and preview dialog header sentence case
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-assisted-setup/qbd-direct-assisted-setup.component.html
  src/app/shared/components/configuration/preview-dialog/preview-dialog.component.html
Labels: deploy, size/S

#1453 fix: UI fixes from testing
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.html
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
  src/app/shared/components/configuration/configuration-step-header/configuration-step-header.component.html
  src/assets/i18n/en.json
  src/styles.scss
Labels: size/S

#1454 fix: revert the height of all inputs back to 40px
  src/assets/themes/fyle/fdl.scss
  src/styles.scss
Labels: deploy, size/S

#1452 fix: handle Intacct connection expiration in token guard
  src/app/core/guard/intacct-token.guard.ts
  src/app/core/guard/netsuite-token.guard.ts
  src/app/core/guard/qbo-token.guard.ts
  src/app/core/guard/sage300-token.guard.ts
  src/app/core/guard/xero-token.guard.ts
Labels: size/S

#1470 fix: remove unnecessary scroll in Travelperk
  src/app/integrations/business-central/business-central-main/business-central-configuration/business-central-configuration.component.html
  src/app/integrations/business-central/business-central-main/business-central-dashboard/business-central-dashboard.component.html
  src/app/integrations/business-central/business-central-main/business-central-export-log/business-central-complete-export-log/business-central-complete-export-log.component.html
  src/app/integrations/business-central/business-central-main/business-central-export-log/business-central-export-log.component.html
  src/app/integrations/business-central/business-central-main/business-central-export-log/business-central-skipped-export-log/business-central-skipped-export-log.component.html
  src/app/integrations/business-central/business-central-main/business-central-main.component.html
  src/app/integrations/business-central/business-central-main/business-central-mapping/business-central-mapping.component.html
  src/app/integrations/business-central/business-central-onboarding/business-central-onboarding-advanced-settings/business-central-onboarding-advanced-settings.component.html
  src/app/integrations/business-central/business-central-onboarding/business-central-onboarding-connector/business-central-onboarding-connector.component.html
  src/app/integrations/business-central/business-central-onboarding/business-central-onboarding-export-settings/business-central-onboarding-export-settings.component.html
  src/app/integrations/business-central/business-central-onboarding/business-central-onboarding-import-settings/business-central-onboarding-import-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-advanced-settings/business-central-advanced-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-import-settings/business-central-import-settings.component.html
  src/app/integrations/travelperk/travelperk-main/travelperk-configuration/travelperk-configuration.component.html
  src/app/integrations/travelperk/travelperk-main/travelperk-main.component.html
  src/app/integrations/travelperk/travelperk-onboarding/travelperk-onboarding-advanced-settings/travelperk-onboarding-advanced-settings.component.html
  src/app/integrations/travelperk/travelperk-onboarding/travelperk-onboarding-payment-profile-settings/travelperk-onboarding-payment-profile-settings.component.html
  src/app/integrations/travelperk/travelperk-shared/travelperk-advanced-settings/travelperk-advanced-settings.component.html
  src/app/integrations/travelperk/travelperk-shared/travelperk-payment-profile-settings/travelperk-payment-profile-settings.component.html
Labels: size/M

#1467 fix: remove unnecessary scroll in QBD connector
  src/app/integrations/business-central/business-central-main/business-central-configuration/business-central-configuration.component.html
  src/app/integrations/business-central/business-central-main/business-central-dashboard/business-central-dashboard.component.html
  src/app/integrations/business-central/business-central-main/business-central-export-log/business-central-complete-export-log/business-central-complete-export-log.component.html
  src/app/integrations/business-central/business-central-main/business-central-export-log/business-central-export-log.component.html
  src/app/integrations/business-central/business-central-main/business-central-export-log/business-central-skipped-export-log/business-central-skipped-export-log.component.html
  src/app/integrations/business-central/business-central-main/business-central-main.component.html
  src/app/integrations/business-central/business-central-main/business-central-mapping/business-central-mapping.component.html
  src/app/integrations/business-central/business-central-onboarding/business-central-onboarding-advanced-settings/business-central-onboarding-advanced-settings.component.html
  src/app/integrations/business-central/business-central-onboarding/business-central-onboarding-connector/business-central-onboarding-connector.component.html
  src/app/integrations/business-central/business-central-onboarding/business-central-onboarding-export-settings/business-central-onboarding-export-settings.component.html
  src/app/integrations/business-central/business-central-onboarding/business-central-onboarding-import-settings/business-central-onboarding-import-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-advanced-settings/business-central-advanced-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-export-settings/business-central-export-settings.component.html
  src/app/integrations/business-central/business-central-shared/business-central-import-settings/business-central-import-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-configuration/qbd-direct-configuration.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-complete-export-log/qbd-direct-complete-export-log.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-export-log/qbd-direct-export-log.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-main.component.html
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-mapping/qbd-direct-mapping.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-advanced-settings/qbd-direct-onboarding-advanced-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-connector/qbd-direct-onboarding-connector.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-export-settings/qbd-direct-onboarding-export-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-import-settings/qbd-direct-onboarding-import-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-onboarding/qbd-direct-onboarding-pre-requisite/qbd-direct-onboarding-pre-requisite.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-advanced-settings/qbd-direct-advanced-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-import-settings/qbd-direct-import-settings.component.html
  src/app/integrations/qbd/qbd-main/qbd-configuration/qbd-configuration.component.html
  src/app/integrations/qbd/qbd-main/qbd-dashboard/qbd-dashboard.component.html
  src/app/integrations/qbd/qbd-main/qbd-main.component.html
  src/app/integrations/qbd/qbd-main/qbd-mapping/qbd-generic-mapping/qbd-generic-mapping.component.html
  src/app/integrations/qbd/qbd-main/qbd-mapping/qbd-mapping.component.html
  src/app/integrations/qbd/qbd-onboarding/qbd-onboarding-advanced-setting/qbd-onboarding-advanced-setting.component.html
  src/app/integrations/qbd/qbd-onboarding/qbd-onboarding-export-setting/qbd-onboarding-export-setting.component.html
  src/app/integrations/qbd/qbd-onboarding/qbd-onboarding-field-setting/qbd-onboarding-field-setting.component.html
  src/app/integrations/qbd/qbd-shared/qbd-advanced-setting/qbd-advanced-setting.component.html
  src/app/integrations/qbd/qbd-shared/qbd-export-setting/qbd-export-setting.component.html
  src/app/integrations/qbd/qbd-shared/qbd-field-mapping/qbd-field-mapping.component.html
  src/app/integrations/qbd/qbd.component.html
  src/app/integrations/sage300/sage300-main/sage300-configuration/sage300-configuration.component.html
  src/app/integrations/sage300/sage300-main/sage300-dashboard/sage300-dashboard.component.html
  src/app/integrations/sage300/sage300-main/sage300-export-log/sage300-complete-export-log/sage300-complete-export-log.component.html
  src/app/integrations/sage300/sage300-main/sage300-export-log/sage300-export-log.component.html
  src/app/integrations/sage300/sage300-main/sage300-export-log/sage300-skipped-export-log/sage300-skipped-export-log.component.html
  src/app/integrations/sage300/sage300-main/sage300-main.component.html
  src/app/integrations/sage300/sage300-main/sage300-mapping/sage300-mapping.component.html
  src/app/integrations/sage300/sage300-onboarding/sage300-onboarding-advanced-settings/sage300-onboarding-advanced-settings.component.html
  src/app/integrations/sage300/sage300-onboarding/sage300-onboarding-connector/sage300-onboarding-connector.component.html
  src/app/integrations/sage300/sage300-onboarding/sage300-onboarding-export-settings/sage300-onboarding-export-settings.component.html
  src/app/integrations/sage300/sage300-onboarding/sage300-onboarding-import-settings/sage300-onboarding-import-settings.component.html
  src/app/integrations/sage300/sage300-shared/sage300-advanced-settings/sage300-advanced-settings.component.html
  src/app/integrations/sage300/sage300-shared/sage300-export-settings/sage300-export-settings.component.html
  src/app/integrations/sage300/sage300-shared/sage300-import-settings/sage300-import-settings.component.html
  src/app/integrations/travelperk/travelperk-main/travelperk-configuration/travelperk-configuration.component.html
  src/app/integrations/travelperk/travelperk-main/travelperk-main.component.html
  src/app/integrations/travelperk/travelperk-onboarding/travelperk-onboarding-advanced-settings/travelperk-onboarding-advanced-settings.component.html
  src/app/integrations/travelperk/travelperk-onboarding/travelperk-onboarding-payment-profile-settings/travelperk-onboarding-payment-profile-settings.component.html
  src/app/integrations/travelperk/travelperk-shared/travelperk-advanced-settings/travelperk-advanced-settings.component.html
  src/app/integrations/travelperk/travelperk-shared/travelperk-payment-profile-settings/travelperk-payment-profile-settings.component.html
Labels: size/M

#1474 feat: add active state for toggles
  src/styles.scss
Labels: size/XS

#1476 fix: dashboard progress bar and count
  src/app/integrations/qbd-direct/qbd-direct-main/qbd-direct-dashboard/qbd-direct-dashboard.component.ts
Labels: size/XS

#1475 fix: loader size for onboarding page
  src/app/shared/components/helper/app-landing-page-header/app-landing-page-header.component.html
  src/assets/themes/co/c1dl.scss
  src/assets/themes/co/primitives_variables.scss
  src/assets/themes/fyle/fdl.scss
  src/assets/themes/fyle/primitives_variables.scss
  tailwind.config.js
Labels: size/S

#1462 fix: token expiry and re-connect screen freezing issue (Sage 300, Intacct, NetSuite)
  src/app/integrations/sage300/sage300-onboarding/sage300-onboarding-connector/sage300-onboarding-connector.component.ts
  src/app/shared/components/netsuite/core/netsuite-connector/netsuite-connector.component.ts
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.ts
Labels: staging_deploy, size/XS

#1481 ui: update dropdown colors to match carbon
  src/assets/themes/fyle/fdl.scss
  src/assets/themes/fyle/primitives_variables.scss
  src/styles.scss
  tailwind.config.js
Labels: size/S

#1480 ui: table headers + dropdown colors
  .github/pr-checks-config.yml
  src/assets/themes/fyle/fdl.scss
  src/assets/themes/fyle/primitives_variables.scss
  src/styles.scss
  tailwind.config.js
Labels: size/L

#1484 feat: rebranding font/border/bg/navbar style changes
  src/app/integrations/landing-v2/landing-v2.component.scss
  src/app/shared/components/helper/app-landing-page-body/app-landing-page-body.component.html
  src/app/shared/components/menu/main-menu/main-menu.component.html
  src/assets/scss/tab-primary.scss
  src/assets/themes/fyle/fdl.scss
  src/assets/themes/fyle/primitives_variables.scss
Labels: size/M

#1485 fix: calendar styling
  src/app/shared/components/configuration/configuration-skip-export/configuration-skip-export.component.html
  src/app/shared/components/si/helper/skip-export/skip-export.component.html
  src/styles.scss
  tailwind.config.js
Labels: size/S
