Repository fylein/fyle-integrations-app, pull requests merged in 2025-02, with the labels that each got.

#1172 fix: beta badge positioning
  src/app/integrations/landing-v2/landing-v2.component.html
Labels: size/XS

#1171 fix: logo size + font size fixes
  src/app/integrations/landing-v2/landing-v2.component.html
Labels: size/XS

#1170 fix: reorder tiles to alphabetical order
  src/app/integrations/landing-v2/landing-v2.component.html
Labels: size/M

#1176 feat: seatch icon focus state styling
  src/app/branding/c1-style-config.ts
  src/app/branding/fyle-style-config.ts
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.html
  src/app/shared/components/configuration/configuration-confirmation-dialog/configuration-confirmation-dialog.component.ts
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.html
  src/app/shared/components/configuration/email-multi-select-field/email-multi-select-field.component.ts
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.html
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.ts
  src/app/shared/components/input/search/search.component.html
  src/app/shared/components/input/search/search.component.ts
Labels: size/S

#1177 feat: qbd direct dashboard info box update
  src/app/shared/components/dashboard/dashboard-export-section/dashboard-export-section.component.html
Labels: size/XS

#1180 chore: Remove PII info for external apps
  src/app/core/services/integration/refiner.service.ts
  src/app/core/services/integration/tracking.service.spec.ts
  src/app/core/services/integration/tracking.service.ts
  src/app/integrations/integrations.component.ts
Labels: deploy, size/XS

#1181 chore: deploy to all staging envs
  .github/workflows/c1-staging-deployment.yml
  .github/workflows/qa-deployment.yml
  .github/workflows/staging-deployment.yml
Labels: size/S

#1157 feat: fixes for support of skip expense post import
  src/app/integrations/qbo/qbo-main/qbo-dashboard/qbo-dashboard.component.html
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.html
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.ts
Labels: deploy, size/XS

#1178 feat: branding based content changes fix
  src/app/integrations/intacct/intacct-shared/intacct-c1-import-settings/intacct-c1-import-settings.component.html
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-data-sync/qbd-direct-data-sync.component.html
  src/app/integrations/qbd-direct/qbd-direct-shared/qbd-direct-export-settings/qbd-direct-export-settings.component.html
  src/app/integrations/qbo/qbo-onboarding/qbo-clone-settings/qbo-clone-settings.component.html
  src/app/integrations/qbo/qbo-shared/qbo-export-settings/qbo-export-settings.component.html
  src/app/integrations/xero/xero-onboarding/xero-clone-settings/xero-clone-settings.component.html
  src/app/integrations/xero/xero-shared/xero-export-settings/xero-export-settings.component.html
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
  src/app/shared/components/configuration/configuration-mapping-fields/configuration-mapping-fields.component.html
  src/app/shared/components/configuration/configuration-select-field/configuration-select-field.component.html
  src/app/shared/components/configuration/configuration-skip-export/configuration-skip-export.component.html
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.html
  src/app/shared/components/export-log/export-log-table/export-log-table.component.html
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.html
  src/app/shared/components/helper/mapping/generic-mapping-v2/generic-mapping-v2.component.html
  src/app/shared/components/qbd/mapping/qbd-mapping-table/qbd-mapping-table.component.html
  src/app/shared/components/si/core/intacct-location-entity/intacct-location-entity.component.html
  src/app/shared/components/si/helper/dashboard-mapping-resolve/dashboard-mapping-resolve.component.html
  src/app/shared/components/si/helper/skip-export/skip-export.component.html
Labels: size/M

#1187 fix: casing bug in field initialization making the field display 'null'
  src/app/core/models/xero/xero-configuration/xero-import-settings.model.ts
Labels: size/XS

#1186 feat: hide error section conditionally skip export v2
  src/app/integrations/business-central/business-central-main/business-central-dashboard/business-central-dashboard.component.html
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.html
  src/app/integrations/netsuite/netsuite-main/netsuite-dashboard/netsuite-dashboard.component.html
  src/app/integrations/sage300/sage300-main/sage300-dashboard/sage300-dashboard.component.html
  src/app/shared/components/dashboard/dashboard-error-section/dashboard-error-section.component.ts
Labels: size/XS

#1188 fix: branding condition for import settings page
  src/app/integrations/intacct/intacct-main/intacct-configuration/intacct-configuration-routing.module.ts
Labels: size/XS

#1189 fix: vulnerability fixes
  .github/workflows/storybook.yml
  package-lock.json
  package.json
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
Labels: size/XL

#1190 fix:browserTarget to buildTraget conversion
  angular.json
Labels: size/XS

#1185 fix: hide dropdown changes for c1
  src/app/branding/c1-branding-config.ts
  src/app/branding/fyle-branding-config.ts
  src/app/core/models/branding/feature-configuration.model.ts
  src/app/shared/components/menu/main-menu/main-menu.component.html
  src/app/shared/components/menu/main-menu/main-menu.component.ts
Labels: size/XS
