Repository fylein/fyle-integrations-app, pull requests merged in 2025-07, with the labels that each got.

#1368 feat: prettier setup
  .husky/pre-commit
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
Labels: size/M

#1365 fix: token_update_screen fix test cases & code improvements
  src/app/core/services/sage300/sage300-configuration/sage300-connector.service.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-connector/intacct-onboarding-connector.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.ts
  src/app/integrations/intacct/intacct.component.spec.ts
  src/app/integrations/sage300/sage300-onboarding/sage300-onboarding-connector/sage300-onboarding-connector.component.ts
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.ts
  src/app/shared/components/netsuite/core/netsuite-connector/netsuite-connector.component.ts
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.spec.ts
Labels: size/M

#1348 feat: Sage Intacct reconnection dialog
  src/app/core/guard/sage300-token.guard.spec.ts
  src/app/core/guard/sage300-token.guard.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/sage300/sage300-configuration/sage300-connector.model.ts
  src/app/core/models/sage300/sage300-configuration/sage300-onboarding-stepper/sage300-onboarding-stepper.model.ts
  src/app/core/services/sage300/sage300-configuration/sage300-connector.service.ts
  src/app/core/services/sage300/sage300-configuration/sage300-onboarding.service.ts
  src/app/core/services/si/si-core/intacct-connector.service.ts
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-connector/intacct-onboarding-connector.component.html
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-connector/intacct-onboarding-connector.component.spec.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-connector/intacct-onboarding-connector.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.html
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.scss
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.ts
  src/app/integrations/intacct/intacct.component.spec.ts
  src/app/integrations/intacct/intacct.component.ts
  src/app/integrations/sage300/sage300-main/sage300-dashboard/sage300-dashboard.component.html
  src/app/integrations/sage300/sage300-main/sage300-dashboard/sage300-dashboard.component.ts
  src/app/integrations/sage300/sage300-onboarding/sage300-onboarding-connector/sage300-onboarding-connector.component.html
  src/app/integrations/sage300/sage300-onboarding/sage300-onboarding-connector/sage300-onboarding-connector.component.ts
  src/app/integrations/sage300/sage300-routing.module.ts
  src/app/integrations/sage300/sage300-shared/sage300-connection-form/sage300-connection-form.component.html
  src/app/integrations/sage300/sage300-shared/sage300-connection-form/sage300-connection-form.component.scss
  src/app/integrations/sage300/sage300-shared/sage300-connection-form/sage300-connection-form.component.spec.ts
  src/app/integrations/sage300/sage300-shared/sage300-connection-form/sage300-connection-form.component.ts
  src/app/integrations/sage300/sage300.component.ts
  src/app/shared/components/configuration/configuration-text-field/configuration-text-field.component.html
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.html
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.ts
  src/app/shared/components/netsuite/core/netsuite-connector/netsuite-connector.component.ts
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.html
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.spec.ts
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.ts
  src/app/shared/shared.module.ts
Labels: size/L

#1343 feat: token expiry detection module for sage intacct
  src/app/core/guard/intacct-token.guard.spec.ts
  src/app/core/guard/intacct-token.guard.ts
  src/app/core/guard/sage300-token.guard.spec.ts
  src/app/core/guard/sage300-token.guard.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/sage300/sage300-configuration/sage300-connector.model.ts
  src/app/core/models/sage300/sage300-configuration/sage300-onboarding-stepper/sage300-onboarding-stepper.model.ts
  src/app/core/services/sage300/sage300-configuration/sage300-connector.service.ts
  src/app/core/services/sage300/sage300-configuration/sage300-onboarding.service.ts
  src/app/core/services/si/si-core/intacct-connector.service.ts
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.html
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-connector/intacct-onboarding-connector.component.html
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-connector/intacct-onboarding-connector.component.spec.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-connector/intacct-onboarding-connector.component.ts
  src/app/integrations/intacct/intacct-routing.module.ts
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.html
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.scss
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.ts
  src/app/integrations/intacct/intacct.component.spec.ts
  src/app/integrations/intacct/intacct.component.ts
  src/app/integrations/sage300/sage300-main/sage300-dashboard/sage300-dashboard.component.html
  src/app/integrations/sage300/sage300-main/sage300-dashboard/sage300-dashboard.component.ts
  src/app/integrations/sage300/sage300-onboarding/sage300-onboarding-connector/sage300-onboarding-connector.component.html
  src/app/integrations/sage300/sage300-onboarding/sage300-onboarding-connector/sage300-onboarding-connector.component.ts
  src/app/integrations/sage300/sage300-routing.module.ts
  src/app/integrations/sage300/sage300-shared/sage300-connection-form/sage300-connection-form.component.html
  src/app/integrations/sage300/sage300-shared/sage300-connection-form/sage300-connection-form.component.scss
  src/app/integrations/sage300/sage300-shared/sage300-connection-form/sage300-connection-form.component.spec.ts
  src/app/integrations/sage300/sage300-shared/sage300-connection-form/sage300-connection-form.component.ts
  src/app/integrations/sage300/sage300.component.ts
  src/app/shared/components/configuration/configuration-text-field/configuration-text-field.component.html
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.html
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.ts
  src/app/shared/components/netsuite/core/netsuite-connector/netsuite-connector.component.ts
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.html
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.spec.ts
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.ts
  src/app/shared/shared.module.ts
Labels: size/M

#1284 feat: Netsuite reconnection dialog
  src/app/core/guard/intacct-token.guard.spec.ts
  src/app/core/guard/intacct-token.guard.ts
  src/app/core/guard/sage300-token.guard.spec.ts
  src/app/core/guard/sage300-token.guard.ts
  src/app/core/models/enum/enum.model.ts
  src/app/core/models/sage300/sage300-configuration/sage300-connector.model.ts
  src/app/core/models/sage300/sage300-configuration/sage300-onboarding-stepper/sage300-onboarding-stepper.model.ts
  src/app/core/services/netsuite/netsuite-core/netsuite-connector.service.ts
  src/app/core/services/sage300/sage300-configuration/sage300-connector.service.ts
  src/app/core/services/sage300/sage300-configuration/sage300-onboarding.service.ts
  src/app/core/services/si/si-core/intacct-connector.service.ts
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.html
  src/app/integrations/intacct/intacct-main/intacct-dashboard/intacct-dashboard.component.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-connector/intacct-onboarding-connector.component.html
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-connector/intacct-onboarding-connector.component.spec.ts
  src/app/integrations/intacct/intacct-onboarding/intacct-onboarding-connector/intacct-onboarding-connector.component.ts
  src/app/integrations/intacct/intacct-routing.module.ts
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.html
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.scss
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.spec.ts
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.ts
  src/app/integrations/intacct/intacct.component.spec.ts
  src/app/integrations/intacct/intacct.component.ts
  src/app/integrations/netsuite/netsuite-main/netsuite-dashboard/netsuite-dashboard.component.ts
  src/app/integrations/netsuite/netsuite-onboarding/netsuite-onboarding-connector/netsuite-onboarding-connector.component.html
  src/app/integrations/netsuite/netsuite-onboarding/netsuite-onboarding-connector/netsuite-onboarding-connector.component.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-connection-form/netsuite-connection-form.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-connection-form/netsuite-connection-form.component.scss
  src/app/integrations/netsuite/netsuite-shared/netsuite-connection-form/netsuite-connection-form.component.spec.ts
  src/app/integrations/netsuite/netsuite-shared/netsuite-connection-form/netsuite-connection-form.component.ts
  src/app/integrations/netsuite/netsuite.component.ts
  src/app/integrations/sage300/sage300-main/sage300-dashboard/sage300-dashboard.component.html
  src/app/integrations/sage300/sage300-main/sage300-dashboard/sage300-dashboard.component.ts
  src/app/integrations/sage300/sage300-onboarding/sage300-onboarding-connector/sage300-onboarding-connector.component.html
  src/app/integrations/sage300/sage300-onboarding/sage300-onboarding-connector/sage300-onboarding-connector.component.ts
  src/app/integrations/sage300/sage300-routing.module.ts
  src/app/integrations/sage300/sage300-shared/sage300-connection-form/sage300-connection-form.component.html
  src/app/integrations/sage300/sage300-shared/sage300-connection-form/sage300-connection-form.component.scss
  src/app/integrations/sage300/sage300-shared/sage300-connection-form/sage300-connection-form.component.spec.ts
  src/app/integrations/sage300/sage300-shared/sage300-connection-form/sage300-connection-form.component.ts
  src/app/integrations/sage300/sage300.component.ts
  src/app/shared/components/configuration/configuration-text-field/configuration-text-field.component.html
  src/app/shared/components/configuration/configuration-text-field/configuration-text-field.component.ts
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.html
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.scss
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.ts
  src/app/shared/components/helper/onboarding-stepper/onboarding-stepper.component.html
  src/app/shared/components/helper/onboarding-stepper/onboarding-stepper.component.ts
  src/app/shared/components/netsuite/core/netsuite-connector/netsuite-connector.component.html
  src/app/shared/components/netsuite/core/netsuite-connector/netsuite-connector.component.ts
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.html
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.spec.ts
  src/app/shared/components/si/core/intacct-connector/intacct-connector.component.ts
  src/app/shared/shared.module.ts
Labels: size/L

#1375 feat: token_update_screen_for_intacct_netsuite_sage300 dashboard content changes
  src/app/shared/components/dashboard/dashboard-token-expired/dashboard-token-expired.component.html
  src/assets/i18n/en.json
Labels: deploy, size/XS

#1381 chore: i18n keys eslint error fix
  src/app/core/services/intacct/intacct-configuration/export-settings.service.ts
  src/app/core/services/netsuite/netsuite-core/netsuite-connector.service.ts
  src/app/core/services/sage300/sage300-configuration/sage300-connector.service.ts
  src/app/core/services/si/si-core/intacct-connector.service.ts
  src/app/core/services/travelperk/travelperk-advanced-settings.service.ts
  src/app/core/services/travelperk/travelperk-payment-profile-settings.service.ts
  src/app/integrations/intacct/intacct-main/intacct-main.component.ts
  src/app/integrations/intacct/intacct-shared/intacct-connection-form/intacct-connection-form.component.html
  src/app/integrations/netsuite/netsuite-shared/netsuite-connection-form/netsuite-connection-form.component.html
  src/app/integrations/sage300/sage300-onboarding/sage300-onboarding-connector/sage300-onboarding-connector.component.html
  src/app/integrations/sage300/sage300-shared/sage300-connection-form/sage300-connection-form.component.html
  src/app/shared/components/helper/onboarding-stepper/onboarding-stepper.component.html
  src/app/shared/components/si/core/intacct-location-entity/intacct-location-entity.component.ts
  src/assets/i18n/en.json
Labels: size/M

#1376 feat: use custom eslint rules from fyle-eslint-plugin
  .eslintrc.json
  package-lock.json
  package.json
Labels: size/S

#1384 fix(e2e): add aria-labels to mapping header counts
  src/app/shared/components/helper/mapping/mapping-card-header/mapping-card-header.component.html
Labels: size/XS

#1386 fix: add text for single itemized entry to en.json
  src/assets/i18n/co/en.json
  src/assets/i18n/fyle/en.json
Labels: size/XS

#1388 feat: Add Cursor rules for i18n key patterns and fix .gitignore
  .cursor/rules/atomics-i18n-key-pattern.mdc
  .cursor/rules/component-i18n-key-naming.mdc
  .gitignore
Labels: size/M

#1378 fix: q3_usability_issues prevent duplicate fields on dropdown
  src/app/integrations/intacct/intacct-shared/intacct-import-settings/intacct-import-settings.component.html
  src/app/shared/components/configuration/configuration-import-field/configuration-import-field.component.html
  src/app/shared/pipes/exclude-selected-options.pipe.ts
  src/app/shared/shared.module.ts
Labels: deploy, size/S

#1395 fix: Intacct mapping dropdown and hide NetSuite name in JE for c1
  src/app/integrations/netsuite/netsuite-shared/netsuite-export-settings/netsuite-export-settings.component.html
  src/app/shared/components/helper/mapping/generic-mapping-table/generic-mapping-table.component.ts
Labels: size/XS
